candle-core/examples/llama/main.rs
candle-core/src/tensor.rs

- `sum_all` to sum across all dimensions and return a scalar tensor.
- `get` to select an index on the first dimension.
- `flatten` to compress some range of dimensions together.

Add some helper functions

---

candle-hub/Cargo.toml
candle-hub/src/api.rs

Removnig the file lock causing issues on windows.
We're creating the file later instead (if concurrent downloads are happening the `create` should fail). and `rename` instead of `copy` for faster movement.

Remove the unecessary file lock, attempt to rename before copying.

---

candle-core/examples/llama/main.rs
candle-core/src/cuda_backend.rs
candle-core/src/dummy_cuda_backend.rs
candle-core/src/op.rs
candle-core/src/storage.rs
candle-core/src/tensor.rs

Add some map operation so that the dtype matching code is factored out and only required for very custom ops (cast, matmul).

Simplify the dtype matchings in the cuda backend

---

candle-core/examples/llama/main.rs

Add a const to easily tweak the dtype used by llama

---

candle-examples/examples/bert/main.rs
candle-kernels/src/unary.cu

Two small tweaks:
- Add the copy kernels for u8/u32.
- Only apply the necessary pad in the bert example.
- Allow for a batch dimension in the embedding layer.

Minor tweaks.

---

candle-core/src/tensor.rs

This would be broken when using `narrow` or `get` and then `to_scalar` on the resulting tensor.

Bugfix for to_scalar (use the proper start offset).

---

candle-core/src/safetensors.rs

- Without the annotation, I think the rust compiler assumes it's all u8.
It did segfault trying to load `Roberta`.

Fixing unsafe slow load (memcpy).

---

candle-examples/Cargo.toml
candle-examples/examples/bert/main.rs
candle-examples/examples/llama/main.rs
candle-examples/examples/whisper/main.rs
candle-hub/Cargo.toml
candle-hub/src/api/mod.rs
candle-hub/src/api/sync.rs
candle-hub/src/api/tokio.rs
candle-hub/src/lib.rs

- `api::Api` -> `api::tokio::api` (And created new `api::sync::Api`).
- Remove `tokio` from all our examples.
- Using similar codebase for now instead of ureq (for simplicity).

Creating new sync Api for `candle-hub`.

---

candle-examples/examples/bert/main.rs
candle-examples/examples/falcon/main.rs
candle-examples/examples/falcon/model.rs
candle-examples/examples/musicgen/nn.rs
candle-examples/examples/whisper/main.rs
candle-examples/examples/whisper/model.rs
candle-nn/src/lib.rs
candle-nn/src/var_builder.rs

Merge the different codes together, the llama bit is to be rewritten.
This is pending some rewrite of the var-builder so as to untangle it a bit from safetensors, allow different storage and random initialization (based on hints given by the model, e.g. fan-in, fan-out, glorot, etc).

Move the var-builder in a central place.

---

Cargo.toml

Update gemm to a branch that contains both the f16 packing improvement as well as the new wasm-simd version.
Also use this opportunity to fix the CI until the sha256 1.2.0 issue has been fixed https://github.com/baoyachi/sha256-rs/issues/15 .

Gemm update

---

candle-core/src/backend.rs
candle-core/src/backprop.rs
candle-core/src/cpu_backend.rs
candle-core/src/cuda_backend.rs
candle-core/src/dummy_cuda_backend.rs
candle-core/src/op.rs
candle-core/src/storage.rs
candle-core/src/tensor.rs

Add some UnaryOp and BinaryOp enums to reduce the number of top-level cases in the enum variant.

Op refactor

---

candle-core/src/backend.rs
candle-core/src/backprop.rs
candle-core/src/cpu_backend.rs
candle-core/src/lib.rs
candle-core/src/op.rs
candle-core/src/storage.rs
candle-core/src/tensor.rs
candle-core/tests/custom_op_tests.rs

This adds support for handling user defined ops with a single argument (multiple arguments to be added):
- The backward pass can be customised too, it's defined as a function from tensor to tensor so that either it could be done at a high level or another custom op can be used for the backward pass.
- The cuda code can be customised too.

Custom ops with a single argument

---

candle-core/src/cpu_backend.rs
candle-core/src/cuda_backend.rs
candle-core/src/shape.rs
candle-core/src/tensor.rs
candle-core/tests/tensor_tests.rs
candle-examples/examples/bert/main.rs
candle-examples/examples/bert/model.rs
candle-examples/examples/falcon/model.rs
candle-examples/examples/llama/model.rs
candle-examples/examples/musicgen/musicgen_model.rs
candle-examples/examples/musicgen/t5_model.rs
candle-examples/examples/simple-training/main.rs
candle-examples/examples/whisper/main.rs
candle-examples/examples/whisper/model.rs
candle-nn/src/conv.rs
candle-nn/src/layer_norm.rs
candle-wasm-example/src/model.rs
candle-wasm-example/src/worker.rs

And also expose the functions directly on the tensor to avoid having to go through `.shape()` first.

Rename the .r functions to .dims so as to be a bit more explicit.

---

candle-core/src/op.rs
candle-core/src/tensor.rs

This is to ensure that dependencies are properly checked when building the backprop graph.

Add an abstract backprop op type

---

candle-core/src/indexer.rs
candle-core/tests/indexing_tests.rs

Instead have a behavior in line with pytorch which is to return an empty slice.

Do not panic on empty ranges.

---

candle-examples/examples/llama/model.rs
candle-examples/examples/llama_multiprocess/model.rs

One discrepency was the epsilon used in the layer norm (1e-5 vs 1e-6). After fixing this, logits line up pretty well when using float32/cpu.

Line-up the llama implementation with the python-transformers one.

---

candle-examples/Cargo.toml
candle-examples/examples/llama_multiprocess/main.rs
candle-examples/examples/llama_multiprocess/model.rs

- Make the necessary changes for `hf-hub 0.2.0` 
- Use `flash_attn` in that example (it's intended to be a powerhouse example, it's OK to no support non flash imo).
- Remove `use_kv_cache`, same logic being slower doesn't seem really interesting to showcase here.
- Remove resulting dead code.

Making multiprocess require flash-attn.

---

README.md
candle-core/src/safetensors.rs

Depends on https://github.com/LaurentMazare/candle/pull/258 Drafted until merge.

Book 2 (load/save)

---

candle-core/src/backend.rs
candle-core/src/backprop.rs
candle-core/src/cpu_backend.rs
candle-core/src/cuda_backend.rs
candle-core/src/dummy_cuda_backend.rs
candle-core/src/op.rs
candle-core/src/storage.rs
candle-core/src/tensor.rs
candle-core/tests/tensor_tests.rs
candle-examples/examples/musicgen/encodec_model.rs
candle-kernels/src/indexing.cu

The embedding op can be obtained via `index_select` with a target dim of 0, the advantage of `index_select` is that backprop is supported so remove the embedding specific op in favor of this and cleanup the related code.

Remove the embedding ops in favor of index-select.

---

Cargo.toml
candle-core/Cargo.toml
candle-examples/Cargo.toml
candle-flash-attn/Cargo.toml
candle-nn/Cargo.toml
candle-pyo3/Cargo.toml
candle-transformers/Cargo.toml
candle-wasm-examples/llama2-c/Cargo.toml
candle-wasm-examples/whisper/Cargo.toml

It would be nice to find a way to inherit these from the main workspace config.

Add version numbers for all the candle crates

---

candle-core/src/tensor.rs
candle-examples/examples/stable-diffusion/attention.rs
candle-examples/examples/stable-diffusion/clip.rs
candle-examples/examples/stable-diffusion/embeddings.rs
candle-examples/examples/stable-diffusion/main.rs
candle-examples/examples/stable-diffusion/resnet.rs
candle-examples/examples/stable-diffusion/unet_2d.rs
candle-examples/examples/stable-diffusion/unet_2d_blocks.rs
candle-examples/examples/stable-diffusion/utils.rs
candle-examples/examples/stable-diffusion/vae.rs
candle-nn/src/conv.rs
candle-nn/src/group_norm.rs
candle-nn/src/lib.rs
candle-nn/src/ops.rs

This is based on [diffusers-rs](https://github.com/LaurentMazare/diffusers-rs). Multiple models and pipelines have to be converted.
- CLIP for text encoding.
- unet blocks and unet.
- Variational auto-encoder (including sampling).
Missing bits:
- Group-norm.
- Conv2d.
- In utils: upsampling, sigmoid, ...

Add a stable diffusion example

---

README.md

Remove one extra square bracket from the cheatsheet table in the `README.md` file.

Remove extra square bracket from cheatsheet table

---

candle-core/src/cuda_backend.rs

```
error[E0599]: no method named `unwrap_or` found for type `usize` in the current scope
--> candle-core/src/cuda_backend.rs:907:49
|
907 |         let dst_el = p.c_out * l_out * p.b_size.unwrap_or(1);
|                                                 ^^^^^^^^^ method not found in `usize`
```
PR #377 changed a type of `ParamsConv1D::b_size` from `Option<usize>` to regular `usize`, but didn't remove the unwrap in `cuda_backend`. Error only appears when building with `--features cuda`
Fix tested on an AWS `g4s.xlarge` instance with Ubuntu 20.04, CUDA 11.8, NVIDIA driver version: 535.54.03, rust 1.71.0

[candle-core] Remove incorrect unwrap from Conv1d in cuda_backend

---

candle-kernels/src/compatibility.cuh

Without it we can compile for 52 (but I get Operation Not supported
when actually trying to use those kernels).
Fixes partially #353

This is duplicated code on Cuda 12.2.

---

Cargo.toml
candle-core/Cargo.toml
candle-core/src/cpu_backend.rs
candle-core/src/cpu_kernels.rs
candle-core/src/dtype.rs
candle-core/src/lib.rs

This optimizes the cpu implementation for `conv1d`: it changes the loop order so that the operation result in a large dot product and `ggblas` is used to implement this in an efficient way using simd where available. This does not use multiple threads. It is less efficient memory-wise than the naive implementation as the input tensor is made contiguous.
Benchmarking results on my macbook (m2pro 2022).
- On the conv1d benchmark in `candle-core/examples`, the runtime goes from 1.1s to 101ms.
- On whisper, the two first convolutions go from 226ms + 568ms to 30ms + 65ms.

Conv1d optimize

---

candle-kernels/src/compatibility.cuh

Checked on a real windows machine.
The CUDA docs says those functions were introduced in Cuda 12.0 (and absent in Cuda 11.8).
However I run a windows machine on cuda 12.0 which doesn't have these....
Cuda 12.0: https://docs.nvidia.com/cuda/archive/12.0.0/cuda-math-api/group__CUDA__MATH____HALF__COMPARISON.html#group__CUDA__MATH____HALF__COMPARISON
Cuda 11.8: https://docs.nvidia.com/cuda/archive/11.8.0/cuda-math-api/group__CUDA__MATH____HALF__COMPARISON.html#group__CUDA__MATH____HALF__COMPARISON

Compat windows.

---

candle-core/src/cpu_backend.rs

Same as conv1d: re-order the ops to end up doing a large dot product of two vectors and use ggblas to use simd for this portion. There is still no multi-threading and this increases the memory requirement.
Benchmarking on a macbook (m2pro 2022), the `conv2d` case of `cpu_benchmarks.rs` goes from 14.8s to 1.29s.

Optimize the cpu conv2d kernel

---

Cargo.toml
candle-core/Cargo.toml
candle-core/src/cpu_backend.rs
candle-core/src/cpu_kernels.rs
candle-core/src/dtype.rs

This PR parallelize the conv1d and conv2d ops using the rayon thread pool. They do not use par_iter but rather scoped threads as the amount of work for each task is the same. This gives tighter control on thtread allocation at the expense of using heap allocation.
Benchmarks on my macbook pro (m2pro 2022) from `cpu_benchmarks.rs`:
- conv2d benchmark: 1.29s to 271ms.
- conv1d benchmark: 101ms to 20ms.

Parallelise the CPU kernels for the conv ops.

---

README.md
candle-examples/examples/stable-diffusion/main.rs
candle-examples/examples/stable-diffusion/stable_diffusion.rs

Local files can still be used as override but otherwise the default models are retrieved from the HF hub, this should work for stable-diffusion 1.5 and 2.1.

Stable diffusion: retrieve the model files from the HF hub.

---

candle-core/src/safetensors.rs

can directly save the loaded weights.
```rust
let api = Api::new()?;
let repo = api.model("bert-base-uncased".to_string());
let weights = repo.get("model.safetensors")?;
let weights = candle_core::safetensors::load(weights, &Device::Cpu)?;
// do something like this
// ...
candle_core::safetensors::save(&weights, "new-model.safetensors")?;
```

fix: can directly save the loaded weights

---

candle-core/examples/cuda_basics.rs
candle-core/examples/cuda_sum_benchmark.rs
candle-core/src/accelerate.rs
candle-core/src/op.rs
candle-core/tests/grad_tests.rs
candle-core/tests/test_utils.rs
candle-examples/examples/falcon/main.rs
candle-examples/examples/whisper/main.rs
candle-examples/examples/whisper/model.rs

- Use accelerate for point-wise unary and binary functions, similar to mkl.
- Add more tracing to the whisper example.
With these changes, the default whisper example goes from 1.1s to 0.77s on my macbook.

More accelerate optimizations

---

Makefile
candle-core/src/cuda_backend.rs
candle-core/tests/conv_tests.rs
candle-kernels/src/conv.cu

This will be used when cudnn is not available, it's likely to be much less efficient.
Also use this PR as an opportunity to add padding support for conv1d and run the conv tests on both cpu and gpu when cuda is available.

Add a naive conv2d cuda kernel.

---

Cargo.toml
candle-core/Cargo.toml
candle-core/src/cpu/avx.rs
candle-core/src/cpu/kernels.rs
candle-core/src/cpu/mod.rs
candle-core/src/cpu/neon.rs
candle-core/src/cpu/simd128.rs
candle-core/src/cpu_backend.rs
candle-core/src/dtype.rs
candle-core/src/lib.rs

Move some of the simd support bits from ggblas into candle-core, and extend them to support reduce-sum as a first step.
The simd bits will get expanded so as to easily support more ops (e.g. binary ops/max/min/...) and will be helpful to iterate on quantization.
Tested on x86_64 with a speedup of ~5x for `Tensor::sum_keepdims` and on a M2 Pro mac with a speedup of ~10x.

Simd support

---

candle-examples/examples/ggml/main.rs
candle-examples/examples/llama/main.rs

This makes it easy to profile the ggml example and see where the time is spent (80% in the quantized matmul at the moment).

Add some tracing to the quantized example.

---

candle-core/src/op.rs
candle-core/src/quantized/mod.rs
candle-core/src/storage.rs
candle-core/src/tensor.rs
candle-core/tests/custom_op_tests.rs
candle-examples/examples/custom-ops/main.rs
candle-examples/examples/llama_multiprocess/model.rs
candle-flash-attn/src/lib.rs

The `Send + Sync` requirement is only useful for tracking the gradient. Allow for a simpler usage when we don't care about this bit.

Relax the requirements on CustomOp.

---

.cargo/config.toml
candle-core/src/quantized/k_quants.rs

Uses `rayon`'s parallel iterator with size constraints to create reasonable batches for the quantized `vec_dot` function. Achieves ~80% of `llama.cpp`'s speed. 
Maybe this should be replaced by `kernel::par_for_each` or `kernel::par_range` for more fine grained control in the future. 
Also changes the cargo config to always build with `native` cpu features.

Basic `qmatmul` parallelization

---

candle-core/examples/tensor-tools.rs
candle-core/src/npy.rs

Helpful for looking at the content of tensor files from your terminal without having to launch python.
Ideally this will support converting between formats and/or dtype at some point.

Add a tool to inspect tensor files

---

candle-core/src/quantized/k_quants.rs
candle-core/src/quantized/mod.rs
candle-core/src/quantized/neon.rs

Add simd version for neon for the q4_0 and q6k vecdot. Using the q4 llama 7b model, text generation goes from 5.6 tokens/s to 9.3 tokens/s. Generated text is unchanged and the qmatmul tests pass.

Neon support for quantization.

---

README.md

According to the API:
```rust
inp = inp.to_device(&Device::Cuda(0)?)?;
```
cannot work as `Cuda(...)` expects a type `Device` not an integer.
I'd recommend to instead use `new_cuda(...)`

Fix the `?` operator cannot be applied to type `Device` of example

---

candle-core/src/conv.rs
candle-examples/examples/efficientnet/main.rs
candle-nn/src/conv.rs
candle-nn/src/var_builder.rs

Another "modern" vision model, adding it was helpful:
- To fix the group convolutions as these were buggy.
- Understande adaptive-avg-pooling and provide some specialized implementations.

Add Efficientnet

---

README.md
candle-book/src/guide/installation.md

This PR improves the "Installation" section slightly by:
- Making the reader aware that `nvcc` has to be correctly installed and linked
- Making sure that when installing with cuda, one adds: `--features "cuda"` instead of `--features cuda` as `--features cuda` doesn't work in all shells (e.g. it fails in `zsh`)
- Shows the reader how to run the example on GPU

Improve installation section and "get started"

---

candle-core/src/quantized/avx.rs
candle-core/src/quantized/k_quants.rs

Not a massive speedup but got the code-llama 7b q8-0 version from 2.8 token per second to 3.3.

AVX version for the q8-0 multiplications.

---

candle-core/src/lib.rs
candle-core/src/quantized/k_quants.rs
candle-core/src/quantized/neon.rs

Speedup on codellama 7b q8-0: 7.3 token/s -> 8.7 token/s on a macbook pro 14,9 16GB.

Neon intrinsics for the q8_0 vecdot.

---

candle-examples/examples/llama/main.rs
candle-examples/examples/llama/model.rs
candle-examples/examples/llama_multiprocess/main.rs
candle-examples/examples/llama_multiprocess/model.rs

Codellama requires bf16 for now (error to convert from bf16 to f16).
Multiprocess demo not functional for it because flash-attn only supports
f16 for now.
```
cargo run --example llama --release --features cuda -- --dtype bf16 --model-id codellama/CodeLlama-7b-hf --revision refs/pr/3
```
works relatively fast on A10G:
```
100 tokens generated (22.096867654459817 token/s)
```

Adding support for codellama in examples.

---

candle-core/src/quantized/avx.rs
candle-core/src/quantized/k_quants.rs

When using llama-2-7b.ggmlv3.q4_K_M.bin on my ryzen 2600x, inference speed goes from 3.3 token/s to 4.9 token/s.

AVX version of the q4k vecdot.

---

candle-examples/examples/quantized/main.rs

Change the default to match llama.cpp, temperature is set to 0.8, and repeat penalty to 1.1. This changes the default output but the generated texts usually look a lot better. It's still deterministic as the rng seed is fixed and the old behavior can be recovered via `--temperature 0 --repeat-penalty 1`.

Tweak some quantized args

---

candle-nn/src/var_builder.rs

Since a recent change `VarBuilder::get` doesn't panic anymore when a tensor couldn't be found and instead initializes it silently. `VarBuilder::contains_tensor` allows for manually checking wether the tensor exists, but I didn't find any way to figure out what the prefix of the current `VarBuilder` is, which is why I need `VarBuilder::prefix`.
`VarBuilder::set_prefix` is useful when some tensor that isn't on the current path needs to be retrieved, for example when weights are tied.

Allow retrieving and setting prefix of VarBuilder

---

Makefile
candle-pyo3/README.md
candle-pyo3/quant-llama.py
candle-pyo3/test.py

As recommended by @Narsil , using maturin is likely to make things simpler when it comes to deploying potential pip packages and also when just building/testing the pyo3 layer. This PR just adds some very simple maturin setup in which the quantized llama example can be run.

Use maturin

---

candle-core/src/quantized/gguf_file.rs

GGUF was extended by `u64`, `i64` and `f64` types as mentioned [here](https://github.com/ggerganov/ggml/pull/302#issuecomment-1694484996). All ranges were also changed from `u32` to `u64` as someone actually build a file which exceeded the `u32` limit of the tensor sizes. 
This PR allows to read V1 and V2 files, but only V2 files can be created.

Add `GGUFv2` support

---

candle-nn/src/loss.rs

Fix typo in the `nll` function document

Fix typo in the nll function document

---

candle-core/src/cpu_backend.rs

Hi,
Was playing with candle and experimenting with implementing some binary ops present in torch (not in candle) as custom binary ops locally (implementing `CustomOp2`) and would be great to be able to call binary_map, as was possible with unary_map for unary custom ops.

Let outside CustomOp2 implementations use cpu_backend::binary_map/binary_map_vec

---

candle-core/src/shape.rs
candle-core/src/tensor.rs
candle-flash-attn/build.rs

This is a quality of life improvement allowing a construction similar to pytorch use of `-1` when reshaping a tensor, e.g. `t.reshape(5, 2, -1)`, here we use `()` instead of `-1` so as to still be able to use `usize` and to ensure at compile time that there is as single hole, so the equivalent construction becomes `t.reshape((5, 2, ()))?`.

Shape with holes

---

candle-core/src/quantized/k_quants.rs

Found some errors about BlockQ8_1 by comparing the corresponding code in ggml 
- should use int8 type for BlockQ8_1.qs.  The unsigned type would cause great loss for negative weights.
- missing some summation terms of VecDotType(BlockQ8_1) in the vec_dot method of BlockQ4_1 and BlockQ5_1

Fix some errors about BlockQ8_1

---

candle-core/src/lib.rs
candle-core/src/scalar.rs
candle-core/src/tensor.rs
candle-examples/examples/segment-anything/main.rs
candle-examples/examples/segment-anything/model_prompt_encoder.rs

This is not very efficient as we broadcast the values rather than having some dedicated kernels for these, that said it's rare for these ops to represent much computation.

Get the comparison operation to work on scalar values.

---

candle-examples/Cargo.toml
candle-examples/examples/segment-anything/model_image_encoder.rs

Also tried using simd on top of this but it didn't help so most likely we're memory bound for this op at this stage. Fwiw the simd diff:
```diff
diff --git a/candle-core/src/cpu/mod.rs b/candle-core/src/cpu/mod.rs
index 9a8e631..8bc97e2 100644
--- a/candle-core/src/cpu/mod.rs
+++ b/candle-core/src/cpu/mod.rs
@@ -139,6 +139,45 @@ pub(crate) unsafe fn vec_sum(row: *const f32, b: *mut f32, k: usize) {
}
}
+#[cfg(any(
+    target_feature = "neon",
+    target_feature = "avx",
+    target_feature = "simd128"
+))]
+#[inline(always)]
+pub unsafe fn vec_add_cst(dst: *mut f32, src1: *const f32, src2: *const f32, c: f32, k: usize) {
+    let np = k & !(CurrentCpu::STEP - 1);
+
+    if np > 0 {
+        let c = CurrentCpu::from_f32(c);
+        for i in (0..np).step_by(CurrentCpu::STEP) {
+ …
```

Fuse the rel-pos additions via a custom-op.

---

candle-core/src/cuda_backend.rs

On stable diffusion 2.1, a step goes from 3.4s to 0.95s with im2col.

Add Im2Col support on the gpu side.

---

candle-core/src/cpu_backend.rs

As mentioned in #811 the gemm backend panics on unsupported dtypes which is not a good user experience. This  PR adds some simple dtype validation so that a proper error is reported.

Proper error on unsupported dtypes when using gemm.

---

CHANGELOG.md
candle-examples/examples/bigcode/main.rs
candle-examples/examples/falcon/main.rs
candle-examples/examples/llama/main.rs
candle-examples/examples/llama2-c/main.rs
candle-examples/examples/quantized/main.rs
candle-transformers/src/generation/mod.rs
candle-transformers/tests/generation_tests.rs
candle-wasm-examples/llama2-c/lib-example.html
candle-wasm-examples/llama2-c/src/app.rs
candle-wasm-examples/llama2-c/src/bin/m.rs
candle-wasm-examples/llama2-c/src/worker.rs

This is an implementation of nucleus sampling, introduced in the paper [The Curious Case of Neural Text Degeneration](https://papers.labml.ai/paper/1904.09751).
It's supported by [llama-cpp](https://github.com/ggerganov/llama.cpp/blob/d54a4027a6ebda98ab0fef7fa0c2247d0bef132a/llama.h#L444), [llama2.c](https://github.com/karpathy/llama2.c/blob/35deb5e0fa55f0a257040bcf1624ed8386e63dc7/run.c#L631), [open ai](https://platform.openai.com/docs/api-reference/chat/create#top_p) and others.

Implement top_p / nucleus sampling

---

candle-core/src/cuda_backend.rs
candle-kernels/build.rs

On windows, it seems currently `nvcc` will not auto detect `cl.exe` position, so this allows the compiler bindir be stored as an environment variables, for convenience.
This also eliminate a warning under conditional compilation.

Add `CANDLE_NVCC_CCBIN` support for `candle-kernels`, and eliminate warnings.

---

candle-core/src/cuda_backend.rs

This avoids using additional pragma and hopefully will ensure that there is no warning if we move the conv1d to cudnn at some point.

Move the constant to avoid some unused warning.

---

candle-nn/src/activation.rs
candle-transformers/src/models/t5.rs

Hello,
I made some changes to make it possible to load `google/flan-t5-base` and `google/flan-t5-large` models.
Note that there's no actual support for NewGelu, so I'm using the old Gelu.
Output:
```
$ cargo run --example t5 -- --model-id t5-base
...
score: 0.92 'The new movie is awesome' 'The new movie is so great'
score: 0.77 'The cat sits outside' 'The cat plays in the garden'
score: 0.65 'A man is playing guitar' 'A woman watches TV'
score: 0.58 'I love pasta' 'Do you like pizza?'
score: 0.53 'A man is playing guitar' 'The cat plays in the garden'
$ cargo run --example t5 -- --model-id google/flan-t5-base
Finished dev [unoptimized + debuginfo] target(s) in 0.17s
Running `target/debug/examples/t5 --model-id google/flan-t5-base`
...
score: 0.93 'The new movie is awesome' 'The new movie …
```

Add support to flan-t5

---

candle-examples/examples/t5/main.rs

I believe there's a bug in the cache implementation for T5 because I don't get the same output with and without it.
For example, this is without caching:
```bash
% cargo run --release --example t5 -- --model-id "t5-base" --prompt "translate to German: long sentences are not decoded properly" --temperature 0 --decode --use-cache false
...
Lange Sätze werden nicht richtig entschlüsselt
13 tokens generated (16.94 token/s)
```
I don't speak German, but Google translate " Lange Sätze werden nicht richtig entschlüsselt" back to "
Long sentences are not decoded properly".
With cache, I get this:
```bash
$ cargo run --release --example t5 -- --model-id "t5-base" --prompt "translate to German: long sentences are not decoded properly" --temperature 0 --decode --use-cache true
...
Langsames Sätzchen …
```

T5: Add option to override use_cache from config

---

candle-core/src/backprop.rs
candle-core/src/cpu/erf.rs
candle-core/src/cpu/mod.rs
candle-core/src/op.rs
candle-core/src/tensor.rs
candle-core/tests/tensor_tests.rs
candle-kernels/src/cuda_utils.cuh
candle-kernels/src/unary.cu

This is the default implementation for PyTorch gelu activation (whereas candle uses a tanh approximation). Hopefully this will make it easier to line up PyTorch implementation with their candle counterpart.

Add an erf based gelu op

---

candle-examples/examples/t5/main.rs
candle-transformers/src/models/t5.rs

This fixes the issue I mentioned in https://github.com/huggingface/candle/pull/892 and https://github.com/huggingface/candle/pull/864#issuecomment-1724176512
The position biases were not taking into account the cache.
I now get the same output with the two approaches, but somehow, it's slightly slower when the cache is on.  (I have a M2 Mac. I didn't try with a GPU, larger batches, or much larger outputs.)
```bash
$ cargo run --release --example t5 -- --model-id "t5-base" --prompt "summarize: state authorities dispatched emergency crews tuesday to survey the damage after an onslaught of severe weather in mississipi." --temperature 0 --decode
Finished release [optimized] target(s) in 0.18s
Running `target/release/examples/t5 --model-id t5-base --prompt 'summarize: state authorities …
```

Fix T5 kv cache

---

candle-transformers/src/models/t5.rs

In https://github.com/huggingface/candle/pull/840 we added support for Flan T5 and checked the output of the encoder was correct. However, when I added decoding in https://github.com/huggingface/candle/pull/864, I didn't check it also worked for FlanT5. This fixes it.
```bash
$ cargo run --release --example t5 -- --model-id "google/flan-t5-base" --prompt "summarize: state authorities dispatched emergency crews tuesday to survey the damage after an onslaught of severe weather in mississipi." --temperature 0 --decode
Compiling candle-transformers v0.2.3 (/Users/jbochi/dev/github/huggingface/candle/candle-transformers)
Compiling candle-examples v0.2.3 (/Users/jbochi/dev/github/huggingface/candle/candle-examples)
Finished release [optimized] target(s) in 6.04s
Running …
```

Flan T5: Read lm_head when word embeddings are not tied

---

candle-examples/examples/llama_multiprocess/main.rs

The example does not compile without `top_p`

fix: add missing`top_p` in llama_multiprocess

---

candle-core/src/quantized/k_quants.rs
candle-core/src/quantized/simd128.rs
candle-wasm-tests/tests/quantized_tests.rs

This also adds some testing.
For the phi1.5 example in a chrome or a ryzen 2600x, inference for the small model goes from 0.85 token/s to ~4 token/s.

Sketch a simd128 optimized q4k vecdot.

---

candle-examples/examples/segment-anything/main.rs
candle-transformers/src/models/segment_anything/sam.rs
candle-wasm-examples/segment-anything/src/bin/m.rs

These additional points are required not to be part of the generated mask, they can be specified in the command line example via the `-neg-prompt 0.5,0.4` flag.

Add negative prompts to segment-anything.

---

CHANGELOG.md
Cargo.toml
candle-book/Cargo.toml
candle-core/Cargo.toml
candle-datasets/Cargo.toml
candle-examples/Cargo.toml
candle-flash-attn/Cargo.toml
candle-kernels/Cargo.toml
candle-nn/Cargo.toml
candle-nn/src/var_builder.rs
candle-pyo3/Cargo.toml
candle-transformers/Cargo.toml
candle-wasm-examples/bert/Cargo.toml
candle-wasm-examples/llama2-c/Cargo.toml
candle-wasm-examples/phi/Cargo.toml
candle-wasm-examples/segment-anything/Cargo.toml
candle-wasm-examples/t5/Cargo.toml
candle-wasm-examples/whisper/Cargo.toml
candle-wasm-examples/yolo/Cargo.toml
candle-wasm-tests/Cargo.toml

Because of some breaking changes in the segment anything api.
Also remove the deprecated safetensor function.

Bump the version to 0.3.0.

---

candle-examples/examples/quantized-t5/README.md
candle-wasm-examples/t5/index.html
candle-wasm-examples/t5/utils.js

Hey @LaurentMazare . Thanks for reviewing and merging https://github.com/huggingface/candle/pull/1029 so quickly.
As you [suggested](https://github.com/huggingface/candle/pull/1029#issuecomment-1747213867), this updates the [readme of the example](https://github.com/huggingface/candle/tree/main/candle-examples/examples/quantized-t5) and also the wasm demo.
I tested it locally:
I'll see what I can do about advertising this. Creating a quantized model and running it in the browser with Candle was surprisingly easy!

Quant t5: Add coedit model to wasm demo and readme

---

candle-transformers/src/models/quantized_t5.rs
candle-transformers/src/models/t5.rs

I should have deleted this comment in https://github.com/huggingface/candle/commit/05626ef492300a4f99c87555304ec863071722d5 . We do take the sqrt when necessary.

Delete invalid comment in T5 code

---

candle-transformers/src/models/bigcode.rs
candle-transformers/src/models/mixformer.rs
candle-transformers/src/models/quantized_mixformer.rs
candle-transformers/src/models/quantized_t5.rs
candle-transformers/src/models/t5.rs

softmax-last-dim should be (much) more efficient than the usual softmax but can only work on the last dimension and is not supported in backprop.

Use softmax-last-dim where possible.

---

candle-pyo3/e5.py
candle-pyo3/py_src/candle/models/bert.py

This brings the error compared to the reference `transformers` implementation down to ~6e-7 instead of multiple percent.

Use an attention mask in the e5 padding case.

---

Cargo.toml

This avoid the yanked crate that have some bugs, however note that this also requires rust 1.73.

Another gemm update.

---

candle-pyo3/_additional_typing/README.md
candle-pyo3/_additional_typing/__init__.py
candle-pyo3/py_src/candle/__init__.pyi
candle-pyo3/py_src/candle/functional/__init__.pyi
candle-pyo3/py_src/candle/typing/__init__.py
candle-pyo3/py_src/candle/utils/__init__.pyi
candle-pyo3/stub.py

This PR adds the missing typehints for magic methodes e.g. `__add__`. Meaning with this PR the candle  should now be completely typehinted. 
https://github.com/huggingface/candle/assets/65088241/68409e07-89a6-40e2-9f95-ec109a96989d
Since `pyo3` doesn't allow us to set the text signature or even change the doc-string of a magic method the typing information have to be stored externally. For this reason the `candle-pyo3/_additional_typing/__init__.py`  module was created to enable the definition of additional functions for candle classes. The `stub.py` script will import this module and extract all classes from it and combine the function signatures of classes with the same name. 
This means the magic/dunder signatures have to be defined manually in an additional file, if they should be …

PyO3: Add typehinting for magic/dunder methodes

---

.github/workflows/python.yml
candle-pyo3/py_src/candle/models/bert.py

You shouldn't have to trust me, that the tests i add actually pass. This PR adds a simple CI run to perform the following steps: 
- Build via `maturin develop -r`
- Check that all `stub` files match the current implemenetation via: `python stub.py --check`
- Check the formatting via: `black --check .`
- Run the tests via: `python -m pytest -s -v tests`
This CI is only triggered if there were changes in the `candle-pyo3` subdirectory, to not block the normal development of candle.

PyO3: Add CI

---

candle-pyo3/Cargo.toml
candle-pyo3/py_src/candle/__init__.py
candle-pyo3/src/lib.rs

Alright this should add `mkl` support. I also created a quick benchmark script to only test the `matmul` performance between torch and candle:  https://gist.github.com/LLukas22/b58adc148e771afdeaebc4074f0644f7
Results without `--features mkl`:
```
PyTorch: 10.230922899999769
Candle: 3.1102483999998185
```
With `--features mkl`:
```
PyTorch: 10.196486699999696
Candle: 4.144704999999703
```
I'm running this on an AMD Ryzen 7 3700x, ans seeing these results i guess Sarah did a pretty good job optimizing the `gemm` create. 
I also re-ran the embedding "benchmark" and candle still is a bit slower there, but faster than without `mkl`. I'm guessing we lose some speed in other operations than `matmul` or trough the python wrapper. 
With `mkl`:
Without `mkl`:
That being said i'm probably gonna …

PyO3: Add `mkl` support

---

candle-core/src/backprop.rs
candle-core/tests/grad_tests.rs

Implementation of backprop derivative for GELU using the analytical derivative of the GELU approximation 
$$0.5v\left(1+\tanh\left(\sqrt{\frac{2}{\pi}} v(1+0.044715v^{2})\right)\right)$$
as 
$$0.5 + (0.398942 v + 0.0535161 v^3) (1 - \tanh^{2}(0.797885 v + 0.0356774 v^{3})) + 0.5 \tanh(0.797885 v + 0.0356774 v^{3})$$

derivative for GELU

---

candle-core/src/cuda_backend.rs

Fixes crashes that happen whenever an `f64` tensor needs to be copied on the GPU.

fix ucopy for `f64` tensors

---

candle-pyo3/py_src/candle/__init__.pyi
candle-pyo3/src/lib.rs
candle-pyo3/test.py
candle-pyo3/test_pytorch.py

regarding #1087, this PR implements the ability to convert `torch` tensor from/to `candle` tensor as follows:
- `candle` to `torch`: extract `candle` tensor value and use `PyO3` interop to create `torch` tensor.
- `torch` to `candle`: extract `numpy` value from the input `torch` tensor using `PyO3` interop and create `candle` tensor with it.

convert pytorch's tensor in Python API

---

candle-examples/examples/yolo-v8/model.rs
candle-nn/src/batch_norm.rs
candle-nn/src/conv.rs

The BatchNorm2d layer will be absorb into Conv2d, and return a Conv2d which has bias parameter. Whether the Conv2d layer has bias or not, this method can fuse adjacent Conv2d and BatchNorm2d layers together.
**usage:**
```
...
let bn = batch_norm(c2, 1e-3, vb.pp("bn"))?;
let conv = conv2d_no_bias(c1, c2, k, cfg, vb.pp("conv"))?.absorb_bn(&bn)?;
...
```
```
impl BatchNorm {
...
pub fn eps(&self) -> f64 {
self.eps
} 
}
```
- Removed `bn` field in `ConvBlock`
- Add fused_conv for inference
- GPU: NVIDIA GeForce RTX 3060, 12036MiB)
- CPU: 12th Gen Intel(R) Core(TM) i5-12400F
- OS: Ubuntu 23.04
- Model: yolov8s.pt, yolov8s.onnx, yolov8s.safetensors
`cargo run --release --features cuda  --example yolo-v8 -- --model ./yolov8s.safetensors --which s …

Add fuse-conv-bn method for Conv2d

---

candle-core/src/lib.rs
candle-core/src/tensor.rs
candle-examples/examples/mnist-training/main.rs
candle-examples/examples/vgg/main.rs
candle-nn/src/func.rs
candle-nn/src/lib.rs
candle-nn/src/ops.rs
candle-transformers/src/models/vgg.rs

The current `Module` trait just specifies a `forward` method that takes as input a tensor argument. However it's common for layers to have different behavior between the training and evaluation mode, e.g. for dropout or batch-norm. To get around this, PyTorch uses an internal state of the layer that can be eval or train but that's error prone.
Instead we here go with a more explicit/functional approach: we add a new trait `ModuleT` where the forward method also uses a boolean that is true for training and false for evaluation. This can be used directly on tensors via the `apply_t` method (still adding a boolean argument compared to `apply`).
We use this for the vgg model in which the dropout were applied even for evalution, this makes evaluation determinitic. We do not use it in other …

Allow for different behavior between training and eval

---

candle-nn/src/activation.rs
candle-nn/src/ops.rs

I am building a model which use hardsigmoid() activation, basically equals: relu6(x+3) / 6
More details at: [https://pytorch.org/docs/stable/generated/torch.nn.functional.hardsigmoid.html#torch.nn.functional.hardsigmoid](url)
And I found Candle hasn't provide it yet. So This PR is for that.

Add hard-sigmoid and hard-swish activations

---

README.md

Hello everybody,
I have been developing [`candle-vllm`](https://github.com/EricLBuehler/candle-vllm) for the past week now - it is an OpenAI compatible API server that allows you to serve Candle LLMs locally. 
As mentioned in #1247, it currently has a Llama pipeline implemented and will shortly have support for other pipelines (other Candle models) added.
In this PR, I have simply added a link to [`candle-vllm`](https://github.com/EricLBuehler/candle-vllm) in the external resources section. 
Thank you for your consideration!

Add candle-vllm as an external resource

---

README.md

👋 I have been working on a meta-framework built around candle model for the past month called [kalosm](https://github.com/floneum/floneum/blob/master/kalosm/README.md). It provides a higher level API over some models from `candle-tranformers`:
- LLMs (Phi, Mistral)
- Controlled generation support through a [nom](https://github.com/rust-bakery/nom)-like incremental parser combinator framework
- Custom sampler support
- Streaming support
- Embeddings (Bert, Llama through `llm.rs`)
- Document databases with support for fetching data from the web, search engines and local documents in various formats
- Batched embedding support
- Transcription support through Whisper
- Microphone integration (eg. [gather context from the live surroundings](https://github.com/floneum/floneum/blob/master/kalosm/ …

Add Kalosm to the list of external resources

---

candle-core/src/backprop.rs
candle-core/src/op.rs
candle-core/tests/grad_tests.rs

This PR adds backprop support for erf anf gelu-erf.
ERF is based on the erf derivation supplied here: https://en.wikipedia.org/wiki/Error_function and here: https://www.wolframalpha.com/input?i=erf
GELU-ERF is based on the derivation of `0.5x*(1+erf(x/sqrt(2)))` or (`erf(v / 2f64.sqrt()) + 1.) * 0.5 * v`) which can be found here https://www.wolframalpha.com/input?i=0.5x*%281%2Berf%28x%2Fsqrt%282%29%29%29

feat: impl backprop for erf and gelu-erf

---

candle-datasets/src/vision/cifar.rs

This PR add enables the cifar dataset to be downloaded from HF hub similar to the mnist dataset

feat: download cifar dataset parquet files

---

README.md

Candle-onnx dependency prost-build no longer comes bundled with prost binaries causing error when compiling. Added info to readme.md.

Error compiling candle-onnx, added info about missing protoc binaries

---

README.md

Hello everybody,
candle-sampling is a crate that provides various sampling techniques for Candle, including top-p, multinomial, top-k, and soon, beam search. It provides a `LogitsProcessor` similar to the `candle-transformers` version, but with more features. I would appreciate your consideration to add it to the README.

Add candle-sampling to the README

---

.github/workflows/rust-ci.yml
candle-examples/examples/quantized/main.rs

At present both mistral and zephyr models use the same prompt template, which seems to cause unusual behaviour when querying zephyr. I've added a check for use of the zephyr model and added the correct prompt template as specified at https://huggingface.co/TheBloke/zephyr-7B-alpha-GGUF for use in the zephyr case.

Adds check for 7b-zephyr and uses correct template

---

candle-examples/examples/quantized-t5/main.rs
candle-examples/examples/t5/main.rs
candle-transformers/src/models/quantized_t5.rs
candle-transformers/src/models/t5.rs
candle-transformers/src/quantized_var_builder.rs

Google published models trained on [MADLAD400](https://github.com/google-research/google-research/tree/master/madlad_400) that do NMT for 400+ languages and are competitive with much larger models.
It's based on T5, and I - sorry for the shameless plug -, converted it to huggingface's safetensors: https://huggingface.co/jbochi/madlad400-3b-mt
The published weights work with the transformer library, but it doesn't work with candle because of two small things:
- [convert_t5x_checkpoint_to_pytorch.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/convert_t5x_checkpoint_to_pytorch.py) created files with a `decoder.embed_tokens.weight` tensor instead of `shared.weight`. The python code handles both cases. I could manually rename the tensors and reupload the …

Add support for MADLAD400

---

README.md

I think it makes more sense to have it there, since it's a seq2seq model with cross attention, and not a LM. There are also Decoder only T5 models that work as LMs, but that's not the standard.

Update README: Move T5 to Text to Text section

---

candle-core/src/tensor.rs
candle-examples/Cargo.toml
candle-examples/examples/onnx_basics.rs
candle-examples/examples/quantized/main.rs
candle-onnx/src/eval.rs

- Support zephyr-7b-beta.
- Use `TokenOutputStream`.
- Fix the number of generated tokens / generation speed measure.

Quantized model small tweaks

---

candle-nn/src/layer_norm.rs

While porting some code from PyTorch to Candle, I needed to check the values of the weights and biases from LayerNorm layers, but as the values are private they can not be explicitly accessed. 
However, this functionality is present in the Linear layer with the use of two `pub fn weight(&self)` and `pub fn bias(&self)` functions.
I propose adding these two (QOL) functions to the LayerNorm `impl` to match the functionality of the Linear layer, while providing access to the weight and bias Tensors in the LayerNorm layer.

Add weight and bias functions to LayerNorm

---

Cargo.toml
README.md
candle-core/src/op.rs
candle-examples/examples/t5/README.md
candle-examples/examples/t5/main.rs
candle-nn/src/activation.rs
candle-transformers/Cargo.toml
candle-transformers/src/models/mixformer.rs
candle-transformers/src/models/quantized_t5.rs
candle-transformers/src/models/t5.rs

This is yet another variant of the T5 encoder/decoder models.
It works, but it's terribly slow on MacOS. I interrupted the following command after at least 15 minutes, and it had generated just the first 4 words.
```
$ RUST_BACKTRACE=1 cargo run --example t5 --release --features accelerate -- --model-id "google/flan-ul2" --revision "refs/pr/25"  --prompt "A step by step recipe to make bolognese pasta:" --decode
Finished release [optimized] target(s) in 1.06s
Running `target/release/examples/t5 --model-id google/flan-ul2 --revision refs/pr/25 --prompt 'A step by step recipe to make bolognese pasta:' --decode`
Running on CPU, to run on GPU, build this example with `--features cuda`
- In a large skillet
```

Add support to UL2 model family

---

Cargo.toml
candle-core/Cargo.toml
candle-core/src/device.rs
candle-core/src/display.rs
candle-core/src/dummy_metal_backend.rs
candle-core/src/error.rs
candle-core/src/lib.rs
candle-core/src/op.rs
candle-core/src/storage.rs
candle-core/src/tensor.rs
candle-core/src/utils.rs
candle-examples/src/lib.rs
candle-pyo3/src/lib.rs

Empty scaffolding for metal support.

Metal part 1 - Scaffolding for metal.

---

candle-transformers/src/models/t5.rs

Without min function buckets has wrong value in some cases.
In python version this check here - https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L429-L431
After this fix encode has same result between rust and python versions.

Check min to buckets in relative_position_bucket

---

candle-examples/examples/stable-diffusion/main.rs
candle-transformers/src/models/whisper/audio.rs
candle-wasm-examples/whisper/src/audio.rs

fixes
- `clippy::needless-borrows-for-generic-args`
- `clippy::reserve-after-initialization`

fix: address clippy 0.1.74 issues

---

candle-transformers/src/models/trocr.rs

This PR adds `reset_kv_cache` on the following structs
- `TrOCRAttention`
- `TrOCRDecoderLayer`
- `TrOCRDecoder`
- `TrOCRForCausalLM`
- `TrOCRModel` (pub)

feat: adds reset_kv_cache to tocr

---

candle-examples/examples/quantized/main.rs

This MR adds the [OpenChat 3.5](https://huggingface.co/openchat/openchat_3.5/tree/main) model to the quantized example.
Specifically, the GGUF version from https://huggingface.co/TheBloke/openchat_3.5-GGUF/tree/main.
OpenChat is the best 7b model according to Arena ELO https://arena.lmsys.org/
It is a fine tune of mistral, and configuring it as mistral works well.
One prompt:
``` 
$ cargo run --example quantized --release -- --prompt "The best thing about coding in rust is " --which 7b-open-chat-3.5
Compiling candle-examples v0.3.1 (/home/lucas/oss/candle/candle-examples)
Finished release [optimized] target(s) in 4.12s
Running `target/release/examples/quantized --prompt 'The best thing about coding in rust is ' --which 7b-open-chat-3.5`
avx: true, neon: false, simd128: false, f16c: true …
```

Add OpenChat 3.5 to quantized examples

---

candle-examples/examples/quantized/main.rs

On https://github.com/huggingface/candle/pull/1346 this commit https://github.com/huggingface/candle/pull/1346/commits/b5b558a432096976dee2fca48670f2a49b621ddf removed the different tokenizer for OpenChat, but it is required.
Without the tokenizer:
```
$ cargo run --example quantized --release -- --prompt "chat" --which 7b-open-chat-3.5
Compiling candle-examples v0.3.1 (/home/lucas/oss/candle/candle-examples)
Finished release [optimized] target(s) in 4.33s
Running `target/release/examples/quantized --prompt chat --which 7b-open-chat-3.5`
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
loaded 291 tensors (4.37GB) in 0.08s
model built
> Tell me a joke.
User: Tell me a joke.<|end_of_turn|>Assistant: Whythread 'main' panicked at …
```

Examples - Fix OpenChat 3.5 tokenizer

---

README.md

Hi @LaurentMazare,
I have recently added LoRA support to many models in `candle-transformers`. These "LoRA transformers" are in `candle-lora`. However, I think that it would be helpful to add a link for these into the README as it would increase discoverability for developers who want to fine-tune models. Currently, one would need to go to the `candle-lora` repository to find these models, and while that may be intuitive I think making their location explicit would be better.
What do you think about this addition?

Add candle-lora transformers to readme?

---

candle-examples/examples/yolo-v3/main.rs
candle-examples/examples/yolo-v8/main.rs

Noticed that report was quite slow when testing the yolo8 sample.
Doing a bulk copy to CPU reduce process time from 800ms -> 8ms.

Ensure to copy data to cpu before iterating.

---

candle-examples/examples/yolo-v8/main.rs
candle-transformers/src/models/stable_diffusion/utils.rs

This pull request attempts to fix a potential issue in linspace implementation.
`steps` should be strictly greater than 1 to make it consistent with the context (namely, to make it consistent with the error message and to avoid a potential divide-by-zero/NaN).
Although this implementation of linspace is still not completely conformant to the PyTorch equivalent, for example:
```python3
torch.linspace(0.0, 1.0, steps=1)    # tensor([0.])
torch.linspace(0.0, 1.0, steps=0)    # tensor([])
torch.linspace(0.0, 1.0, steps=-1)    # RuntimeError: number of steps must be non-negative
```

Fix linspace implementation

---

README.md
candle-examples/examples/stable-diffusion/main.rs
candle-transformers/src/models/stable_diffusion/ddim.rs
candle-transformers/src/models/stable_diffusion/euler_ancestral_discrete.rs
candle-transformers/src/models/stable_diffusion/mod.rs
candle-transformers/src/models/stable_diffusion/schedulers.rs

This PR added following features  in the stable-diffusion example:
* `--sd-version turbo` 
* `--guidance-scale`  for controlling guidance scale, which SD Turbo need to set it to 0 for the correct result.
you can try this by:
``` bash
cargo run --release --example stable-diffusion --features "cuda,cudnn" -- --prompt "A cinematic shot of a baby racoon wearing an intricate italian priest robe." --use-f16 --sd-version turbo --n-steps 1 --width 512 --height 512 --guidance-scale 0
```

Stable Diffusion Turbo Support

---

candle-examples/build.rs

Allows to use an older version of gcc, for example `CANDLE_NVCC_CCBIN=gcc-12.2`

Add nvcc ccbin support to examples

---

candle-examples/examples/bert/README.md
candle-examples/examples/bert/main.rs
candle-transformers/src/models/bert.rs

This makes the BAAI/bge-large-zh-v1.5 model ~50% faster on my machine (M2 with --accelerate).
See https://github.com/huggingface/candle/issues/1062 for more context (cc @edfix)

Speed up bert with approx gelu

---

candle-metal-kernels/src/tests.rs
candle-metal-kernels/src/unary.metal

This is based on https://github.com/huggingface/candle/pull/1318, which is adding the gelu kernel. cc @Narsil 
The flan t5 embeddings are all NaN when metal is enabled. This is because the output of gelu(x) for x > 10 is NaN.
```
$ cargo run --example t5 --release --features metal -- --model-id "google/flan-t5-small" --prompt "translate to German: A beautiful candle."
[[[NaN, NaN, NaN, ..., NaN, NaN, NaN],
[NaN, NaN, NaN, ..., NaN, NaN, NaN],
[NaN, NaN, NaN, ..., NaN, NaN, NaN],
...
[NaN, NaN, NaN, ..., NaN, NaN, NaN],
[NaN, NaN, NaN, ..., NaN, NaN, NaN],
[NaN, NaN, NaN, ..., NaN, NaN, NaN]]]
Tensor[[1, 9, 512], f32, metal:4294968146]
Took 26.179209ms
```
With this change, I get embeddings approximately equal to the ones I get on the CPU.

Fix NaN errors for Gelu in Metal

---

candle-core/src/backprop.rs
candle-core/src/op.rs
candle-core/src/tensor.rs
candle-core/tests/grad_tests.rs

This should implement backprop for interpolate_2D for a limited set of cases (integer scale factor that is the same for both h and w). However this should be sufficient for common use cases such as unpooling images for deconvolutions (ie when in pytorch Upsample nearest would have been used).

Upsample grad

---

candle-core/src/tensor.rs
candle-core/tests/tensor_tests.rs

A useful tensor function which `candle` do not currently have. 
This function is needed to implement some [missing logic](https://github.com/openai/whisper/blob/e58f28804528831904c3b6f2c0e473f346223433/whisper/decoding.py#L500) of [Whisper](https://github.com/huggingface/candle/issues/1422)
Reference implementation: https://pytorch.org/docs/stable/generated/torch.logsumexp.html#torch-logsumexp

Add logsumexp function

---

candle-wasm-examples/phi/index.html
candle-wasm-examples/phi/phiWorker.js
candle-wasm-examples/phi/src/bin/m.rs

Here the WASM demo for the new Phi-2
The weights are on a different repo, I was getting network error while fetching, so a split it into 500mb chunks
q80 with ~2.5GB didn't load successfully, maybe a memory limit? 
got the `_name_or_path == "microsoft/phi-2"` from the model config in order to the hacked `new_v2`, we can change that later.
Demo: https://huggingface.co/spaces/radames/Candle-phi1-phi2-wasm-demo

Phi 2 wasm 

---

candle-nn/src/var_builder.rs

ShardedSafeTensors load tensors with default hints very slowly, and there's no need to slice them.

Speedup ShardedSafeTensors to load Tensors with default hints

---

candle-transformers/src/models/mistral.rs

Models which use Mistral as a base and the ChatML template format require a different `vocab_size` than using the `config_7b_v0_1` allows.
Adding a new fn should work with all Mistral models using the ChatML template format.
I have tested this in my project and will make another PR to adjust the [mistral cli example](https://github.com/huggingface/candle/blob/main/candle-examples/examples/mistral/main.rs) work with the [Mistral-7B-OpenOrca](https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca) model.
Read more about template formats here:
https://huggingface.co/docs/transformers/main/chat_templating

add fn config_chat_ml

---

candle-transformers/src/models/mistral.rs

I think that this fn name should be more generic since the important consideration is that it uses ChatML and not that it is OpenOrca.
Having `open_orca` in the fn name may lead to confusion, and I don't think we need to add another fn `config_open_hermes_chat_ml`, as that would lead to a lot of code duplication with a few more models.
To make that clear I have included another comment with a link to OpenHermes.
The extra tokens added are:
```json
"<|im_end|>": 32000,
"<|im_start|>": 32001
```
I followed your lead and linked to the original [OpenHermes-2.5-Mistral-7B](https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B) repo in the code, however neither of those repos include a `tokenizer.json` file.
It is not complicated to create one assuming an understanding of what is needed. …

make fn name generic

---

candle-transformers/src/models/mistral.rs
candle-transformers/src/models/quantized_mistral.rs

This PR simply adds `clear_kv_cache` to the `Attention`, `DecoderLayer` and `Model` structs, for both mistral and quantized mistral. 
**TLDR; helpful when calling `forward` more than once to avoid reinitializing the model

feat: add `clear_kv_cache` to mistral and qmistral models

---

candle-nn/src/batch_norm.rs
candle-nn/tests/batch_norm.rs

Ports the [dfdx implementation](https://github.com/coreylowman/dfdx/blob/main/dfdx/src/nn/layers/batch_norm1d.rs) of batch norm training to candle, which unfortunately requires breaking changes. 
- Changes the type of `running_mean` and `running_var` from `Tensor` to `Var`. I'm not sure if this is an intended use of `Var`, but it seemed to be the best fit for this use case.
- Removes `num_features` parameter and adds `momentum` parameter to `new` and `new_no_bias` methods. The `num_features` parameter is redundant with the size of the given tensors.
- Adds a `forward_t` method that shadows the `ModuleT` implementation. This makes batchnorm more intuitive in a `ModuleT` context, but could create confusion or have unexpected behavior for some use cases. Without this, however, …

[Breaking] Add training to batchnorm with exponential moving average

---

candle-examples/examples/stable-diffusion/README.md

Move out the --sd-version flag out of the prompt.

Format properly the Stable Diffusion example run with params

---

candle-nn/src/encoding.rs
candle-nn/src/lib.rs
candle-nn/tests/one_hot.rs

One-hot/cold encoding.
Given an input tensor of indices, this function returns a tensor of the same shape as the input
tensor with an additional dimension of the given depth size. The values in the returned tensor are
all set to the `off_value` except for the positions represented by the indices, which are set to the `on_value`.
This method returns a tensor with a rank that is one rank larger than the input tensor.
As an example, the following tensor will be encoded to a one-hot matrix:
`[[0i64, 2], [1, -1]]`
with a depth of 4 will be encoded to:
`[[[1, 0, 0, 0], [0, 0, 1, 0]], [[0, 1, 0, 0], [0, 0, 0, 0]]]`
When the input tensor index has a value of -1, the corresponding one-hot vector will be ignored,
resulting in a vector of values set to the `off_value`.
This method supports one-cold …

Add one-hot/cold encoding

---

candle-core/src/metal_backend.rs
candle-metal-kernels/src/cast.metal

```
cargo run --example mistral --release --features metal -- --model-id mistralai/Mistral-7B-Instruct-v0.2 --prompt 'Write hello world code in Rust' --sample-len 1
```

Adding bfloat16 support for the cast kernels.

---

README.md

This adds a [link to a port](https://github.com/jeroenvlek/gpt-from-scratch-rs) of  this [tutorial](https://www.youtube.com/watch?v=kCc8FmEb1nY) to Candle. I moved all comments from his notebook to this code as well. 
You will also see a struggle between following his variable naming and my own standards ;) I will probably make that more consistent soon.
It is meant as a complement to the other tutorial link and it showcases different sides of the Candle API applied to a toy example, especially for people trying to build a model from scratch (as opposed to loading pre-trained weights).
I'm sure not everything in the port might be idiomatic use of Candle, happy to receive feedback! Just know that it works and I had to dive into the API quite often to find the corresponding functionality. …

Port of Karpathy's Let's Build GPT tutorial to Candle

---

Cargo.toml
candle-book/Cargo.toml
candle-core/Cargo.toml
candle-datasets/Cargo.toml
candle-examples/Cargo.toml
candle-nn/Cargo.toml
candle-onnx/Cargo.toml
candle-pyo3/Cargo.toml
candle-transformers/Cargo.toml
candle-wasm-examples/bert/Cargo.toml
candle-wasm-examples/blip/Cargo.toml
candle-wasm-examples/llama2-c/Cargo.toml
candle-wasm-examples/phi/Cargo.toml
candle-wasm-examples/segment-anything/Cargo.toml
candle-wasm-examples/t5/Cargo.toml
candle-wasm-examples/whisper/Cargo.toml
candle-wasm-examples/yolo/Cargo.toml
candle-wasm-tests/Cargo.toml

-> Move all our packages inside the workspace dependencies, so all folders (except the packages not in the workspace) can just use `workspace = true`. That removes the version number from a lot of places, so there is a single number for the entire workspace in the root `Cargo.toml`.
Packages outside the workspace (flash, kernels, metal-kernels, onnx) still use path dependencies.

[Proposal] Simplifying our internal cargo dependencies.

---

candle-core/src/quantized/neon.rs
candle-core/tests/quantized_tests.rs

Reproduce the issue in #1526 by comparing the optimized and non-optimized version in a situation that triggers the issue.
Bugfix the overflow.

Simpler repro for the neon optimization issue + bugfix

---

.github/dependabot.yml
Cargo.toml

Hi there,
I really like the project, and i was wondering if we can add dependabot to it, to be always up to date regarding deps.
I set it to 5 max PRs and also on weekly only.
Let me know if you want to adjust those params, thanks.

feat: add dependabot to the project

---

.github/dependabot.yml

Sorry, looks like i broke the CI on main.
Just checked and the CI on main is red because of a deprecated field : `open-pull-requests-limit-per-dependency` that is no longer supported by dependabot.
Related to : https://github.com/huggingface/candle/pull/1553

fix: deprecated option field (open-pull-requests-limit-per-dependency)

---

candle-metal-kernels/src/cast.metal

ifdef directive is not properly closed here which causes error.

Remove redundant metal version check

---

candle-transformers/src/models/phi.rs

Also fix a bug in the KV cache.

Fix the rotary embeddings for the new phi implementation.

---

candle-examples/examples/stable-lm/README.md
candle-examples/examples/stable-lm/main.rs
candle-transformers/src/models/stable_lm.rs

Add Stable-Code, StableLM-2 and Zephyr variants for V1 and V2. For completeness also added the V1 variant from the stabilityai repos (same as the existing one which I renamed to V1Orig). The GGUF quantized versions of the newer models use llama.cpp tensor names that are different from the ones used in the non-quantized model so I did not add those.

Add StableLM-2, StableLM Code and Zephyr variants

---

candle-transformers/src/models/llama.rs

Added derive Clone so that I can pass the model around my app in State.
Added derive Debug because that's what is used in other models.

make llama derive clone

---

candle-nn/src/var_builder.rs

`candle-nn` already exposes a trait to define custom backends. However, it's not possible to actually construct a `VarBuilder` with a custom backend because the constructor is not exposed.
This change makes the constructor public and renames it from `new` to `from_backend` to avoid that it is seen as the primary constructor (which could be confusing to users).

Add `VarBuilder::from_backend`

---

candle-transformers/src/models/whisper/audio.rs
candle-transformers/src/models/whisper/model.rs
candle-transformers/src/models/whisper/quantized_model.rs

This PR adds support for multithreaded workers in `log_mel_spectrogram_` and significantly speeds up the `pcm_to_mel` step.
On an Apple M3 Max this adds a ~6-7x speed up `139.284375ms` -> `21.299458ms` using the following commands
```bash
cargo run --release --example whisper --features metal
```
additionally there are a few new tests that can be run
```bash
cargo test --package candle-transformers --lib -- models::whisper::audio::tests --nocapture
```
**note this speed up is particularly useful with smaller models since the `pcm_to_mel` can take as much time or more as the decoding step on some backends (cuda, metal) so in those cases `pcm_to_mel` is no longer the bottleneck

feat: support multithread spectrogram and small perf tweaks

---

candle-examples/examples/qwen/main.rs

Using the chatglm one causes a bug where the "<|endoftext|>" is not
found.

Fix: the qwen tokenizer location.

---

candle-core/src/backprop.rs
candle-core/src/tensor.rs
candle-core/src/variable.rs
candle-examples/examples/reinforcement-learning/ddpg.rs
candle-examples/examples/reinforcement-learning/policy_gradient.rs
candle-nn/src/batch_norm.rs
candle-pyo3/py_src/candle/__init__.pyi
candle-pyo3/py_src/candle/nn/container.py
candle-pyo3/py_src/candle/nn/module.py
candle-pyo3/py_src/candle/nn/normalization.py
candle-pyo3/py_src/candle/onnx/__init__.pyi
candle-pyo3/src/lib.rs
candle-pyo3/stub.py
candle-wasm-examples/segment-anything/README.md

Detach the tensors on batch-norm eval.

---

candle-core/src/quantized/dummy_metal.rs
candle-core/src/quantized/metal.rs
candle-core/src/quantized/mod.rs

Prepare for adding cuda quantized kernels: remove most of the conditional compilation via the same "dummy module" hack as for the normal storage/device and move the metal specific bits in their own module.

Qmetal tweaks

---

candle-core/src/backprop.rs
candle-core/src/op.rs
candle-core/src/tensor.rs
candle-core/tests/grad_tests.rs

This adds gradients for interpolate1d: this is done in the same manner as for interpolate2d by using a convolution to sum the grads for integer scaling factors, and checked manually in a similar way

Add  grads for interpolate1d

---

candle-examples/examples/segformer/README.md
candle-examples/examples/segformer/assets/labels.json
candle-examples/examples/segformer/main.rs
candle-transformers/src/models/mod.rs
candle-transformers/src/models/segformer.rs

this is a copy from the [huggingface pytorch model][1].
this is inference only so i omitted the parts about dropout, etc.
the model outputs a tensor with shape `[batch_size, num_labels]` where the last dim is logits
the model outputs a tensor with shape `[batch_size, num_labels, height // 4, width // 4]` to represent each 4-pixel patch's logits
this shall give you `burger` label:
```text
classification logits [3.275261e-5, 0.0008562019, 0.0008868563, 0.9977506, 0.0002465068, 0.0002241473, 2.846596e-6]
label: hamburger
```
input image (url is https://huggingface.co/datasets/hf-internal-testing/fixtures_ade20k/resolve/main/ADE_val_00000001.jpg):
output segmentation image:
[1]: https://huggingface.co/docs/transformers/en/model_doc/segformer

Add an initial Segformer implementation

---

candle-core/src/metal_backend.rs
candle-core/src/quantized/ggml_file.rs
candle-core/src/quantized/metal.rs
candle-nn/src/ops.rs

* Simplify new buffer with data approach.
* Use powers of two for buffer sizes so reuse is more likely.
* Select best available buffer by size.
* Add count to MetalStorage -> facilitates using buffers of different size
* Increase default compute_per_buffer to 50 (this should ideally be calculated wrt GPU capabilities and the model being run)
Tested Phi 1.5 on M3 18gb RAM:
Initial load 4.5s -> 2.8s
Total memory usage 9.9 to 7.4 gb
Observed lower memory usage as inference progresses. Ref the flatter graph below. Worth noting that the y-axis is smaller in the front window.
Similar results observed on the M1 Pro 32gb. (Thanks for testing @aorticweb 🤗 )

Improve metal buffer usage

---

candle-nn/src/ops.rs

Derives clone for a dropour layer, mildly useful as it allows models with a dropout layer to derive clone themselves and makes it consistent with Linear and Conv layers deriving clone

Add clone to candle dropout

---

candle-core/src/metal_backend.rs
candle-core/tests/tensor_tests.rs
candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/random.metal

The Metal-engine's random-generation is a bit buggy:
* There was a buffer overrun when explicitly seeding the RNG.
* The seed buffer's usage was not properly setup, and the "Read" usage would be masked by the "Write" usage setting.
* In the shader the seed buffer's contents was not used, but its address, leading to determinism across every random generation request.
* Evenly sized tensors had the element with index N/2 deterministically left as zero.
The PR also contains a check that two consecutive random tensors does not repeat.  This is a suboptimal test in that it conceivably could return a false negative, but from my perspective, that is extremely unlikely.
With these changes, the modified test succeeds.
Edit: Removed point about non-deterministic seeding per process.  The proposed …

Metal random-generation bug fixes

---

candle-core/src/metal_backend.rs
candle-metal-kernels/src/indexing.metal
candle-metal-kernels/src/tests.rs

As the title mentions, adds support on the metal backend for u8 and i64 indices, and f16 and bf16 input tensors for the scatter-add operation. Ran into this missing functionality while running the optimizers on my M1.
This PR also adds some coverage for all of these operations across a few scenarios.
I'm not entirely sure this is the correct approach here, nor am I sure if I am missing anything glaring.

Add support for index u8/i64 and input f16/bf16 scatter-add on metal

---

candle-core/src/metal_backend.rs
candle-metal-kernels/src/cast.metal
candle-metal-kernels/src/tests.rs

This PR aims to remove the discrepancy of casting DTypes for Metal. I've gone ahead and refactored the tests as well to group them appropriately.
One area of the change that I'm uncertain of is the version support, there was a callout to metal version 220 in the code which I preserved, but I could not find any documentation from Apple on these versions and which casts are supported in what release... Guidance on this would be great!

Add support for casting between all supported datatypes on Metal

---

candle-core/src/metal_backend.rs
candle-metal-kernels/src/indexing.metal
candle-metal-kernels/src/tests.rs

There seemed to have been an original implementation of most of the dtypes supported on metal, but the match statement was never updated. 
I have also added test coverage for this operation.

Update supported index-add dtypes for Metal backend

---

candle-core/src/metal_backend.rs
candle-core/tests/pool_tests.rs
candle-metal-kernels/src/conv.metal
candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/tests.rs

Adds support for max_pool2d for metal for the following dtypes:
- f32
- f16
- bf16
- u8
- u32
Essentially a port of the cuda backend implementation but adjusted to the metal backend style.

Add support for max_pool2d for Metal backend

---

candle-core/src/metal_backend.rs
candle-core/tests/pool_tests.rs
candle-metal-kernels/src/conv.metal
candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/tests.rs

Refactored max and avg to share a common method since the only difference is the op name.
Uncommented the metal system test.

Add avg_pool2d metal implementation for the metal backend

---

candle-examples/examples/reinforcement-learning/dqn.rs
candle-examples/examples/reinforcement-learning/main.rs

First of all, thank you for this awesome library!
This PR adds a new example to the `reinforcement-learning` folder based on a DQN agent against the CartPole environment. I've put some effort in making the example as clear as concise as possible.
The example can be run with the following command:
```
cargo run --example reinforcement-learning --features=pyo3 --package candle-examples -- dqn
```

Add a DQN example to the reinforcement-learning section

---

candle-core/src/metal_backend.rs
candle-core/tests/conv_tests.rs
candle-metal-kernels/src/conv.metal
candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/tests.rs

Adds support for the conv_transpose1d function by porting the cuda backend implementation.
Added support for
- f32
- f16
- bf16
- u8
- u32

Add support for conv_transpose1d for metal backend

---

candle-kernels/src/reduce.cu
candle-nn/src/ops.rs
candle-nn/tests/ops.rs

Trying out a custom-op for RmsNorm in order to speed up some transformer architectures (not sure whether the final code will end up in candle-core/candle-nn or elsewhere).
Benchmarks:
- Quantized llama 7b (q4k): 32.5 token/s -> 35.4 token/s (gpu RTX 2080).

Custom op for RmsNorm

---

candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/reduce.metal
candle-nn/src/ops.rs

Benchmark for the quantized llama7b example (q4k) on a M2 macbook pro (M2 pro - 16GB). Before 21.02 token/s, after 21.55 token/s.

RmsNorm kernel for metal.

---

candle-examples/examples/whisper/README.md

Adds the `large-v3` and Distil-Whisper model names to the list of supported checkpoints.

[examples] Update Whisper model names

---

candle-core/src/backend.rs
candle-core/src/cpu_backend.rs
candle-core/src/cuda_backend.rs
candle-core/src/device.rs
candle-core/src/dummy_cuda_backend.rs
candle-core/src/dummy_metal_backend.rs
candle-core/src/metal_backend.rs

This avoids using the cuda blocking api when sending tensors from main memory to the gpu in the case where the memory is owned. This should speed up the loading times of models when using cuda.

Async tensor copying.

---

candle-transformers/src/models/quantized_llama.rs
candle-transformers/src/models/quantized_mistral.rs
candle-transformers/src/quantized_nn.rs

Start using the fused RmsNorm kernel. On a RTX 4080, the mistral example goes from 77 token/s to 85 token/s.

Use the fast RmsNorm in the quantized models.

---

candle-core/src/backend.rs
candle-core/src/cpu_backend.rs
candle-core/src/cuda_backend.rs
candle-core/src/device.rs
candle-core/src/dummy_cuda_backend.rs
candle-core/src/dummy_metal_backend.rs
candle-core/src/metal_backend.rs
candle-core/src/tensor.rs
candle-core/src/tensor_cat.rs

This is mostly similar to #1845 but removes some unnecessary bits, and improve a couple things:
- Marks the added function as unsafe.
- Uninitialize the vecs on the cpu too (which is fairly scary...).
- Proper metal handling and benchmarking.
Benchmark on quantized q4k:
- Cuda on a RTX 4080: 52.6 token/s -> 54.5 token/s.
- Metal (M2 Pro 16GB): 21.0 token/s -> 21.7 token/s.
- CPU: no measurable change on M2 Pro.

Add the alloc_uninit function.

---

candle-kernels/src/cast.cu

- it make possible to load bf16 models on T4(sm75)

Add cast_bf16_x/cast_x_bf16 when CUDA_ARCH<800 but CUDA_VERSION >= 11000

---

candle-core/src/custom_op.rs
candle-core/src/lib.rs
candle-core/src/storage.rs
candle-core/src/tensor.rs
candle-core/tests/custom_op_tests.rs

This PR adds some preliminary support for inplace ops (standard and custom). These ops are key in high performance application to avoid re-allocating buffers over and over + touch generally less memory, however they are tricky to work with. In particular running a backward pass on a forward that used an inplace op is likely to end up being UB.

Preliminary support for inplace ops.

---

candle-kernels/src/reduce.cu
candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/reduce.metal
candle-nn/Cargo.toml
candle-nn/src/lib.rs
candle-nn/src/rotary_emb.rs
candle-nn/tests/ops.rs
candle-transformers/src/models/quantized_llama.rs

Benchmark on the quantized example (llama2-7b - q4k):
- Metal (M2 Pro 16GB): 26.2 token/s -> 28.8 token/s.
- CPU (M2 Pro 16GB): 10.7 token/s, ~unchanged.
- Cuda (RTX 2080): 34.1 token/s -> 36.1 token/s.

Fast kernels for rotary embeddings.

---

candle-core/src/metal_backend.rs
candle-metal-kernels/src/conv.metal

While running f16 models with the stable-diffusion examples I ran into this missing functionality, should help make these examples easier to use in the future for Mac users.

Extend supported dtypes for metal (im2col & upsample_2d)

---

candle-transformers/src/models/mamba.rs

Motivation: Need to have access to Mamba configuration for another repo that depends on `candle`.
Content: Add a function `config_2_8b` for `Mamba`'s `Config`, following https://huggingface.co/docs/transformers/model_doc/mamba.

add config for mamba 2.8b model parameter

---

candle-transformers/src/models/stable_diffusion/schedulers.rs

Motivation: This small change is needed if we want to operate `StableDiffusion` models across threads.

add send and sync trait bounds for scheduler config in stable diffusion models 

---

candle-core/src/tensor_cat.rs
candle-transformers/src/models/quantized_llama.rs

These calls actually don't have any performance impact as `contiguous` doesn't do any copy if the input is already contiguous. However they can be confusing when reading the code so getting rid of them.

Remove some unnecessary calls to contiguous.

---

candle-core/src/quantized/cuda.rs
candle-examples/examples/quantized/main.rs
candle-kernels/src/quantized.cu

These kernels are experimental for now, they can be tried out in the `quantized` example via the `--fast-cuda` flag.
As a benchmark,
```
cargo run --example quantized --profile=release-with-debug --features cuda -- --prompt "Building a website can be done in 10 simple steps:\nStep 1:" -n 100 --which 7b-mistral --fast-cuda
```
This goes from 33 token/s to 63 token/s with the new kernels, whereas llama.cpp is at ~55 token/s using the same model (mistral-7b-v0.1.Q4_K_S.gguf from TheBloke).

More ggml cuda kernels

---

candle-core/src/quantized/cuda.rs
candle-examples/examples/mistral/main.rs
candle-examples/examples/quantized/main.rs

This tweak the default to use the faster q8-1 quantization kernels, will be released once they have been battle tested a bit more.

Switch the default to using the faster kernels.

---

candle-core/src/lib.rs

Currently writing a custom backend for candle and ran into module access issues as I can't access the structs defined here, this change enables this for me!

Modify access for conv and op to public

---

candle-transformers/src/models/falcon.rs

Motivation: In order to build a falcon's `Config` type from a `config.json` file, it is usually simpler to deserialize it directly, using serde.

derive serde's deserialize trait for falcon's config

---

candle-core/src/cuda_backend/mod.rs
candle-kernels/src/cuda_utils.cuh
candle-nn/src/rnn.rs
candle-transformers/src/models/segment_anything/prompt_encoder.rs

Ran the tests without any issue. This also include a change in the RNN layout which was broken prior to this change.
Model tested:
- Llama (quantized and unquantized).
- Mistral (quantized and unquantized).
- Stable diffusion.
- Qwen1.5 + the MoE variant.
- Encodec.
- Vision: resnet, blip, efficientnet.
- Segment anything (this includes an unrelated fix to get it to work with cuda).
- RWKV.
- Mamba.
- Clip.

Relax the contiguous check for cuda kernels.

---

candle-metal-kernels/src/reduce.metal

There should not be a change to any of the actual logic here, this PR is just aiming to make this file friendlier to edit by reducing the amount of code that is wrapped in the CPP macro.
Note: I'm not as familiar with passing functions as references as done in the reduce change I've made here, open to recommendations.

Refactor metal reduce kernel to be more readable/friendly to changes

---

candle-transformers/src/models/mixformer.rs

When running the moondream example on a 7950x, this reduces the `load_t` step from 7.13s to 6.46s.

Faster mask implementation for mixformers.

---

candle-examples/examples/moondream/main.rs
candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/unary.metal

This uses an implementation similar to mlx for the kernel as well as the dispatch ([mlx kernel](https://github.com/ml-explore/mlx/blob/bddf23f175726a57f0e443cd45518c0757daa166/mlx/backend/metal/kernels/copy.metal#L32), [mlx dispatch](https://github.com/ml-explore/mlx/blob/bddf23f175726a57f0e443cd45518c0757daa166/mlx/backend/metal/copy.cpp#L129)).
On my M2 Pro 16G, the quantized default example goes from 34.0 token/s to 35.4 token/s after this change (generating 100 tokens).

Optimize copy-2d for metal.

---

candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

This PR adds support for the "ReduceMean" onnx operation based on https://onnx.ai/onnx/operators/onnx__ReduceMean.html#reducemean-13
The onnx model that I'm trying to load was generated with https://github.com/huggingface/optimum, and that tool generates the version 13 of the "ReduceMean" operation, so I have implemented a version compatible with 13 and below.
There do is a new version 18 with different inputs (`axes` comes as a second input rather than a named attribute), but I have not seen a clear path for switching between the different versions of an operation in order to provide different implementations.
A clean way I can imagine of doing is would be to split `candle-onnx/src/eval.rs` into one file per operation, implement all the versions of an operation in each file, and heavily …

Add ReduceMean onnx operation

---

candle-transformers/src/models/t5.rs

This change avoids crashes when running T5 models with F16 tensors on CPU.

Avoid crashes when running T5 models with F16 tensors on CPU

---

candle-core/benches/bench_main.rs
candle-core/benches/benchmarks/mod.rs
candle-core/benches/benchmarks/qmatmul.rs

Adds benchmarks for the qmatmul operation across all the different dtypes, will be useful moving forwards as we tune or adjust our quantized kernels.

Add benchmarks for qmatmul operations

---

candle-examples/examples/trocr/main.rs

Was getting `Error: device mismatch in conv2d, lhs: Cpu, rhs: Cuda { gpu_id: 0 }` when running with `--features cuda` but it seems it was just missing the `to_device` call like in https://github.com/huggingface/candle/pull/1856

Move image tensor to device in trocr example

---

candle-core/src/quantized/cuda.rs
candle-kernels/src/quantized.cu

This enables the new "dense" quantized matmul cuda kernels, these kernels are only used for prompt processing.
On a RTX 2080, this makes the prompt processing go from 73 token/s to 98 token/s though it's arguably on as mall prompt.
```
`target/release-with-debug/examples/quantized --model mistral-7b-v0.1.Q4_K_S.gguf --prompt 'Building a website can be done in 10 simple steps:\nStep 1:' -n 100 --which 7b-mistral`
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
loaded 291 tensors (4.14GB) in 0.80s
model built
...
19 prompt tokens processed: 98.22 token/s
99 tokens generated: 63.82 token/s
19 prompt tokens processed: 72.66 token/s
99 tokens generated: 60.80 token/s
```

Faster kernels for quantized matmul on cuda

---

candle-examples/examples/stable-diffusion/README.md
candle-examples/examples/stable-diffusion/main.rs

Utilize batches in Stable Diffusion that were already there, but unutilized in the examples file.
Also refactor out the `save_image` function.

Utilize batches in Stable Diffusion 

---

candle-core/src/quantized/cuda.rs
candle-core/tests/quantized_tests.rs
candle-kernels/src/quantized.cu

Only handling the batch sizes up to 4 to avoid including too many kernels.
See #2074 and https://github.com/ggerganov/llama.cpp/pull/5351#issue-2119377523 for more context.

Add the mmv kernels for small batch sizes.

---

candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

Follow up for https://github.com/huggingface/candle/pull/2049
Adds the following onnx operations along with tests based on the official onnx examples for the following operations:
- Sqrt
- Range
- Greater
- Less
- Log
- Min
- Where
Additionally, fixes support for the following operations, also adding tests:
- ConstantOfShape
---
With this, I was able to run MusicGen's text encoder onnx model, but there's still something wrong, even though the model now runs successfully, the output is:
```
[[[NaN, NaN, NaN, ..., NaN, NaN, NaN],
[NaN, NaN, NaN, ..., NaN, NaN, NaN]]]
Tensor[[1, 2, 768], f32]
```
I've verified that my the onnx file is correct (I can run it successfully with https://github.com/pykeio/ort), so there must be something else in `candle-onnx` that is not working correctly.

Add missing onnx operations

---

candle-nn/src/layer_norm.rs
candle-transformers/src/models/llama.rs
candle-transformers/src/models/with_tracing.rs

The llama example was still using the very slow rms-norm variant, this switches it (and all other models) to use the faster kernel.
On a H100 with flash-attn enabled, generation speed for llama-v3 8b goes from 74.4 token/s to 88.4 token/s.

Use the faster rms-norm kernel for llama.

---

candle-core/src/backend.rs
candle-core/src/cpu_backend/mod.rs
candle-core/src/cuda_backend/device.rs
candle-core/src/device.rs
candle-core/src/dtype.rs
candle-core/src/dummy_cuda_backend.rs
candle-core/src/dummy_metal_backend.rs
candle-core/src/lib.rs
candle-core/src/metal_backend/mod.rs
candle-core/src/tensor.rs

Currently when loading a model on cuda or metal, there is an additional copy taking place to get a `CpuStorage` from the original data slice and pass it to the device. This is not necessary but hard to get around with the current types so this PR adds a new `CpuStorageRef` type to get around this, the cuda implementation bypasses the additional copy.

Add StorageRef.

---

candle-core/src/variable.rs
candle-nn/tests/batch_norm.rs

Before this change, if you use a `VarMap` to build a `BatchNorm`, then train the `BatchNorm`, the variables for `running_mean` and `running_var` in the `VarMap` won't be updated as the model is trained. That's because it calls `Var::from_tensor` to create those variables, which is creating new variables that aren't tracked in the `VarMap`.
After this change, if the tensor that `batch_norm` gets from the `VarBuilder` is a variable, we will just reuse it instead of creating a new one.
It still feels error prone, since it is possible to create `Var`s that can be updated in `forward_train` without ever being saved, but I'm not sure what the best way to fix it is. Maybe `BatchNorm` shouldn't update `running_mean` and `running_var` if it is created with detached tensors.

Bug Fix: When converting a tensor to a variable, clone if the tensor is already a variable.

---

candle-core/src/metal_backend/device.rs
candle-core/src/metal_backend/mod.rs

As reported in discord, using `try_write` results in `WouldBlock` error on concurrent accesses. Hence in the cpu/cuda backend we always use `write` instead which semantic is to block until the lock has been released. The downside is that it could lead to deadlocks instead, so we have to be cautious about releasing the locks as soon as possible and before potentially trying to lock any other mutex.

Use write rather than try-write on the metal rw-locks.

---

candle-examples/examples/segment-anything/main.rs

Threshold is 0.0 by default, negative values make more points included, expanding the mask. Positive values make it more picky, making the mask smaller.
Negative numbers start with a minus sign, which normally makes clap consider it a flag.
Without this change:
```
$ cargo run --example segment-anything -- --image assets/single_pt_prompt.jpg --point 0.5,0.5 --threshold -0.5
error: unexpected argument '-0' found
Usage: segment-anything [OPTIONS] --image <IMAGE>
For more information, try '--help'.
```

Allow the threshold argumet to be negative in the segment-anything example

---

candle-examples/examples/gte-qwen/README.md
candle-examples/examples/gte-qwen/main.rs
candle-examples/examples/qwen/main.rs
candle-transformers/src/models/qwen2.rs

gte-Qwen1.5-7B-instruct is a variant of the GTE embedding model family.
- Model card: https://huggingface.co/Alibaba-NLP/gte-Qwen1.5-7B-instruct
- Technical report: https://arxiv.org/abs/2308.03281 
This is a text embedding model based on Qwen2. They share same model architecture except the last `lm_head` module. This commit brings in minimal modification of the old Qwen2 implementation to support both models.
An example is provided, which had been verified according to the official PyTorch implementation.

Support embedding model gte-Qwen1.5-7B-instruct

---

candle-core/src/tensor_cat.rs
candle-core/tests/tensor_tests.rs
candle-examples/examples/quantized-phi/main.rs
candle-nn/src/kv_cache.rs
candle-nn/src/lib.rs
candle-transformers/src/models/quantized_phi3.rs

`dst.slice_set(src, dim, offset)` corresponds to `dst[..., offset:offset+src.shape[dim], ...] = src` in PyTorch, this operation is in place so not compatible with backprop.
The main motivation for this is to be able to write an efficient kv-cache that would be compatible with the flash attention kernels.
The quantized-phi3 model has been adapted. Profile before the change when generating a new token after having generated ~150 tokens:
After the change:
As expected the first copy2d operations disappear, removing ~6us on my RTX 4080 (so sparing roughly 384 us per token - though the matmul after that might be slower as it's strided differently, flash-attn will help gettingaround this).

Add a slice_set op.

---

candle-examples/examples/quantized-phi/main.rs
candle-nn/src/kv_cache.rs
candle-transformers/src/models/quantized_phi3.rs

This call did not seem to be necessary and removing it result in some large speedups. When generating ~500 tokens.
- Cuda (4080 super):  161 tok/s -> 180 tok/s.
- Cpu (7950X): 16.4 tok/s -> 16.7 tok/s.
- Metal (MBP M2 16GB 14,9): 35.3 tok/s -> 44.1 tok/s.
- Cpu (MBP M2 16GB 14,9): 18.3 tok/s -> 19.4 tok/s.

Avoid a contiguous call in the quantized phi 3 model.

---

candle-nn/src/layer_norm.rs
candle-nn/tests/layer_norm.rs
candle-transformers/src/models/phi.rs

Tested on phi-2 as nowadays almost every uses rmsnorm instead. Speed went from 48 token/s to 51 token/s on a RTX 4080 Super. (and to 53 token/s by also updating the rope kernel).
Note that this is a breaking change: we don't use a broadcasting addition/multiplication anymore and instead require the alpha/beta of the layer norm to have the appropriate shape (i.e. be 1d with the same number of elements as the last dimension of the input tensor).

Enable the new layer-norm.

---

candle-transformers/src/models/moondream.rs

Helps with compatibility with serde_json and giving the ability to clone the config. Similar usage as Blip.

Add Debug, Clone, Deserialize to moondream config

---

Cargo.toml

This should bring support for cuda 12.5, release notes [here](https://github.com/coreylowman/cudarc/releases/tag/v0.11.2).

Update cudarc to 0.11.2.

---

Cargo.toml

A new cudarc version was just released which:
- Uses nvcc to find CUDA toolkit
- Adds a fix for finding curand

Bump cudarc version to 0.11.4

---

candle-datasets/src/vision/mnist.rs

Attempting to load the MNIST dataset currently results in a somewhat confusing error `Api error: Header etag is missing`, which seems to be a symptom of the dataset simply not existing. 
This can be reproduced with
```
use candle_datasets::vision::mnist;
fn main() {
mnist::load().unwrap();
}
```

Fix dataset id for MNIST

---

candle-core/src/quantized/gguf_file.rs

This PR implements what is described in #2243: automatically upcasting GGUF values for which a lossless conversion can be made. I have implemented this only for `gguf_value::Value::to_u64` for ease of review, and this can easily be extended to the other methods.

Automatically upcast GGUF values

---

candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

Added operators ArgMin, ArgMax and LeakyRelu together with tests.
I am aware of the PR by socathie https://github.com/huggingface/candle/pull/2231 which includes ArgMin, but because it wasn't merged yet I included my implementation of it in this PR together with the other operators.

ONNX: add ArgMin, ArgMax and LeakyRelu

---

candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

The intent of this change is to allow eval of the current silero_vad.onnx (v4). This onnx file uses 'If' and 'Pad' nodes, which had not been supported by onnx::simple_eval until now.

implement if, and pad reflect mode

---

candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

As part of my effort to get silero_vad v4 running, I have also implemented the onnx "Slice" operation.
This change also contains a small fix for the "Cast" operator, specifically to support onnx "bool" datatypes which I've chosen in the "If" op to be represented as u8. This needed a small change to the `dtype` helper function to pass through "Cast" correctly.

onnx eval: implement Slice op

---

candle-examples/Cargo.toml
candle-examples/examples/depth_anything_v2/README.md
candle-examples/examples/depth_anything_v2/color_map.rs
candle-examples/examples/depth_anything_v2/main.rs
candle-nn/src/ops.rs
candle-transformers/src/models/depth_anything_v2.rs
candle-transformers/src/models/dinov2.rs
candle-transformers/src/models/mod.rs

This PR adds [Depth Anything V2](https://depth-anything-v2.github.io/), which is based on the already present DinoVisionTransformer.  I'm still adding the [Spectral-R coloring](https://huggingface.co/spaces/depth-anything/Depth-Anything-V2/blob/main/run.py#L51), but this led me to another question on the list, so I thought it wise to open a (preliminary) PR to get some early answers and feedback. So here goes:
1. Currently the port is following the Python code very closely. However, the separation of concerns in the original code is not necessarily the level of encapsulation I would have chosen (e.g. the scratch layer is accessed from the head). What is your standpoint here: Stick to the original code as closely as makes sense, or improve it where you can?
2. Can I add palette as a dep to …

Depth Anything v2

---

candle-examples/examples/phi/main.rs

I tried out the sample command provided in the README.md file:
```
$ cargo run --example phi --release -- --model 2 \
--prompt "A skier slides down a frictionless slope of height 40m and length 80m. What's the skier speed at the bottom?"
...
loaded the model in 12.820701458s
starting the inference loop
A skier slides down a frictionless slope of height 40m and length 80m. What's the skier speed at the bottom?
Solution:
The potential energy of the skier is converted into kinetic energy as it slides down the slope. The formula for potential energy is mgh, where m is mass, g is acceleration due to gravity (9.8 m/s^2), and h is height. Since there's no friction, all the potential energy is converted into kinetic energy at the bottom of the slope. The formula for kinetic energy is 1/2mv^2, …
```

make up for the missing last token output of phi2 example

---

candle-examples/examples/eva2/README.md
candle-examples/examples/eva2/main.rs
candle-transformers/src/models/eva2.rs
candle-transformers/src/models/mod.rs

Hi,
I have implemented the EVA-02 model ( https://arxiv.org/abs/2303.11331 ), an improvement of the BeiT model (with a custom Y-shaped feed-forward, absolute positional encoding at beginning + rotate positional encoding in the attention module.
This model currently ranks first in ImageNet classification, according to timm.
( See: https://github.com/huggingface/pytorch-image-models/blob/main/results/results-imagenet.csv )
The weights provided are for ImageNet classification, and come from timm.
Thanks for your time,
Regards,
Vincent.
PS: As it was the case with the BeiT model implementation, there will be another commit / pull request later on, related to the rotate positional encoding. For now, I have included the weights as a single additional tensor, to the safetensor weights (+0.5 MB …

Add EVA-02 model ( https://arxiv.org/abs/2303.11331 )

---

Cargo.toml

This PR pins `cudarc` to a known working version and resolves #2331. I have tested this change across two official nvidia cuda containers. One with a version prior to support (`nvidia/cuda:12.0.0-cudnn8-devel-ubuntu20.04`) and one post (`nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04`) and the examples I tested work as expected.

Pinning cudarc to 0.11.6

---

candle-core/src/backprop.rs

Current Elu backward pass implementation produce `NaN` when an argument is a large positive number.
Let variable `x` has value:
```
[ -3.0092e2,  -2.7229e2,  -2.4637e2,  -2.2293e2,  -2.0171e2,  -1.8252e2,
-1.6515e2,  -1.4943e2,  -1.3521e2,  -1.2234e2,  -1.1070e2,  -1.0017e2,
-9.0633e1,  -8.2008e1,  -7.4203e1,  -6.7141e1,  -6.0751e1,  -5.4969e1,
-4.9737e1,  -4.5003e1,  -4.0719e1,  -3.6843e1,  -3.3336e1,  -3.0162e1,
-2.7290e1,  -2.4691e1,  -2.2339e1,  -2.0211e1,  -1.8286e1,  -1.6543e1,
-1.4965e1,  -1.3538e1,  -1.2246e1,  -1.1076e1,  -1.0018e1,  -9.0596e0,
-8.1919e0,  -7.4063e0,  -6.6948e0,  -6.0502e0,  -5.4663e0,  -4.9370e0,
-4.4571e0,  -4.0219e0,  -3.6269e0,  -3.2682e0,  -2.9422e0,  -2.6456e0,
-2.3756e0,  -2.1293e0,  -1.9043e0,  -1.6984e0,  -1.5095e0,  -1.3357e0,
-1.1752e0,  -1.0265e0, …
```

Fix Elu gradient NaN on large input

---

candle-examples/examples/clip/README.md

I going through examples in the project and I noticed that the CLIP example README title was different (probably a mistake) than other examples.
I tried following the same standard as done in these files:
- `./candle-examples/examples/blip/README.md`
- `./candle-examples/examples/trocr/README.md`
- `./candle-examples/examples/marian-mt/README.md`
- `./candle-examples/examples/segformer/README.md`

Fix CLIP example README title

---

candle-wasm-examples/bert/src/bin/m.rs

This PR changes DTypes from F64 to F32 to allow the example to run and to match the DTypes in candle-transformers. Fixes #2355.

Change DTypes in candle-wasm-examples/bert (fixes #2355)

---

Cargo.toml

In the image crate [v0.25.0](https://docs.rs/image/0.25.0/image/index.html#high-level-api) it seems you're expected to alias the reader ala `use image::io::Reader as ImageReader;`, while in [0.25.2 (latest)](https://docs.rs/image/latest/image/index.html#high-level-api) it is available directly.
This resolves these errors:
> error[E0433]: failed to resolve: could not find `ImageReader` in `image`
--> candle-examples/src/imagenet.rs:6:22
|
6 |     let img = image::ImageReader::open(p)?
|                      ^^^^^^^^^^^
|                      |
|                      could not find `ImageReader` in `image`
|                      help: a trait with a similar name exists: `ImageDecoder`

Bump image crate version so ImageReader is available without aliasing

---

candle-core/src/metal_backend/mod.rs
candle-metal-kernels/src/affine.metal

This fixes the SAM example when running on metal.

Enable the affine kernel for u8/u32.

---

candle-core/src/tensor.rs
candle-core/tests/tensor_tests.rs

Fixing #2356
For the updated unit test case, the current `log_sum_exp(-1)` yields `[[3.4076, 6.4076], [-inf, inf]]`.  With this fix, the result will be `[[3.4076, 6.4076], [-998.5924, 1001.4076]]`, which matches the output from pytorch.

Fix log_sum_exp to handle large positive/negative inputs

---

candle-core/src/backprop.rs

Discussion in https://github.com/huggingface/candle/discussions/2377 
This PR adds `get_ids` function to `GradStore` that returns the list of `TensorId` in the store. It can be used to implement optimizers that only update relevant variables stored in the store. The typical use case is the word2vec model, which has many embeddings for the words but updates only a few in each iteration.

Add get_ids to GradStore (Discussion #2377)

---

candle-nn/src/rnn.rs

I added the `pub`  keyword to the fields in `LSTMState` and `GRUState` to make the states public, so that a state can be created using a predefined initial state tensor from a pretrained model.
See previous related closed [PR #2368 ](https://github.com/huggingface/candle/pull/2368).

update: LSTMState and GRUState fields to be public

---

candle-core/src/backprop.rs

This pull request exploits some mathematical properties of the `silu` operation. By reusing the computed forward pass results as much as possible, the optimized code reduces the running time for a sliver of a millisecond.
Ideally, since the forward pass also calculates the sigmoid of the input, if we could cache that intermediate result somehow, we can avoid computing that again, further cutting down some time.
By the way, the type of `silu_grad` is `Result<Tensor, Error>`, yet the compiler still accepts the code. Perhaps we don't need so many `?` operators after all.

Optimize gradient for silu a bit

---

candle-transformers/src/object_detection.rs
candle-transformers/tests/nms_tests.rs

Implements soft non-maximum suppression based on the research article https://arxiv.org/pdf/1704.04503, and also creates basic tests for NMS and Soft-NMS. This implementation of Soft-NMS can be given IOU and Score threshold to fine tune confidence decay.
Implementation of my feature request: #2389

Soft Non-Maximum Suppression

---

.gitignore
candle-examples/examples/parler-tts/decode.py
candle-examples/examples/parler-tts/main.rs
candle-transformers/src/models/mod.rs
candle-transformers/src/models/parler_tts.rs

This adds the generative part of this TTS model, however the DAC part is not handled yet so this still has to be done with python for now. The audio below was generated with the default prompt/conditioner and a temperature of 0, then applying the `decode.py` script to convert the audio tokens to a pcm file.
https://github.com/user-attachments/assets/e65d1d00-afec-4716-a8bb-7af7b2e3c0aa

parler-tts support

---

candle-nn/src/rnn.rs
candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

I'm not sure if, at this point, the simple_eval is the right place to put all this code. It's the thing I implemented, but I could use some direction from code maintainer where this makes sense to add to the codebase.
It was a bit trickier to test this as the docs don't really give inputs/outputs, their tests simply match against an alternative implementation of LSTM. So I've done basically the same thing, where I checked that the implementation here matches the output of pytorch's LSTM node.

onnx: implement LSTM op

---

candle-onnx/src/eval.rs

rather than fully defining pow in the cpu backend (as in #2318), this implements a much smaller change which is sufficient to evaluate silero-vad onnx models. Specifically, checking if we can use `Tensor::powf` which is defined for negative base.

onnx: workaround pow with negative base

---

README.md
candle-examples/examples/fastvit/README.md
candle-transformers/src/models/fastvit.rs

* correct optional SE layer dimensions.
* head_dim instead of num_heads is 32.
* update test example output.

FastViT fixes.

---

candle-examples/examples/mobileclip/README.md
candle-examples/examples/mobileclip/main.rs
candle-examples/examples/mobilenetv4/main.rs
candle-examples/src/imagenet.rs
candle-transformers/src/models/mobileclip.rs
candle-transformers/src/models/mod.rs
candle-transformers/src/models/openclip/mod.rs
candle-transformers/src/models/openclip/text_model.rs

Generic OpenCLIP text encoder and a subset of the Apple MobileCLIP models.

MobileCLIP models S1 and S2

---

candle-examples/examples/flux/main.rs

FLUX repo changed extension for the filenames, this PR addresses this:
`flux1-schnell.sft` -> `flux1-schnell.safetensors`
`flux1-dev.sft` -> `flux1-dev.safetensors`
`ae.sft` -> `ae.safetensors`

Fix FLUX.1 weights

---

candle-metal-kernels/src/unary.metal

Use `precise::tanh` instead of `tanh` to avoid easily generating `NaN` values rather than 1 or -1.

Fix for metal tanh.

---

candle-core/src/lib.rs

This pull request exports `TensorIndexer` to candle lib users, which allows users to implement the `IndexOp` trait with `TensorIndexer` specified as a part of the constraints.
```rust
pub struct CustomStruct {
data: Tensor,
// ...
}
impl<A> IndexOp<A> for CustomStruct
where
A: Into<TensorIndexer>,
{
fn i(&self, index: A) -> Result<Tensor, Error> {
self.data.i(index)
}
}
```

Export ``TensorIndexer` to candle users

---

candle-examples/examples/granite/README.md
candle-examples/examples/granite/main.rs
candle-transformers/src/models/granite.rs
candle-transformers/src/models/mod.rs

Hey team!
Than you very much for sharing your work :)
Granite LLM models have a very interesting Open Source license (Apache 2.0) and perform very well in many benchmarks.
There might be many potential Candle users who might be interested in this integration.
So far, I just copied the Llama example and adapted it, so for the 7B Instruct was really straightforward.
If the community is interested, I'll be adding support for the rest of the models :)
Cheers!

Adding Granite 7b Instruct model example

---

candle-core/src/metal_backend/device.rs
candle-core/src/metal_backend/mod.rs
candle-metal-kernels/src/utils.rs

Centralize the command encoding part of the metal backend so that it's easier to switch for a version that re-uses encoders.

Metal commands refactoring

---

Cargo.toml
candle-flash-attn/Cargo.toml
candle-kernels/Cargo.toml
candle-metal-kernels/Cargo.toml
candle-onnx/Cargo.toml

Bump to a new major version as the previous metal changes break the existing api.

Bump the crate version.

---

Cargo.toml

This makes candle compatible with cuda 12.6.

Update cudarc to 0.12.1.

---

candle-examples/examples/mimi/main.rs
candle-nn/src/kv_cache.rs
candle-nn/tests/kv_cache.rs
candle-transformers/src/models/mimi/transformer.rs

This is useful for generating infinite sequences, e.g. for https://github.com/kyutai-labs/moshi/issues/51

Add a RotatingKVCache.

---

candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

- Added 4 ONNX operators, Expand, Split, ReduceSum and ReduceL2
- Fix small issues in Where and Clip operators
- Add some associated tests
There are some more tests that could be added based on the onnx documentation examples, but I wanted to open this PR to get any feedback first, since this would be my first contribution to candle.
My motivation for the changes was to support running a few onnx models (such as https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2).

Expand split ops

---

candle-core/src/quantized/cuda.rs

This fixes the issue when using MMV with quantized flux.
Testing:
- Added a dedicated test.
- Ran flux before / after the change.
- Ran a couple quantized models.

Cuda quantized mmv bugfix.

---

candle-examples/examples/whisper/README.md

When running the command from the Readme of the whisper example:
```
error: target `whisper` in package `candle-examples` requires the features: `symphonia`
Consider enabling them by passing, e.g., `--features="symphonia"`
```
This just adds the suggested flag
fixes #2502

Add required feature for whisper example in Readme

---

candle-examples/examples/bert_masked_lm/main.rs
candle-examples/examples/splade/README.md
candle-examples/examples/splade/main.rs
candle-transformers/src/models/bert.rs

SPLADE models are proving to be quite useful for document retrieval. As there was no Masked LM implementation of BERT, I have added it based on the transformers library implementation. These are the main changes:
1. Add BertForMaskedLM in the Bert Model, which extends the Bert Model for Masked LM tasks like SPLADE. 
2. Added an example to showcase SPLADE. Merging this example is optional as it is very similar to the Bert example but with SPLADE aggregation formula.

Add BertForMaskedLM to support SPLADE Models

---

candle-transformers/src/models/marian.rs

Currently, there is no way to use a Marian model that isn't `opus_mt_tc_big_fr_en` or `opus_mt_tc_big_fr_en`, because the only way to get a Marian config is by calling the functions for those two models configs which are hard coded into the library. This change simply allows you to use serde to deserialize a Marian model's `config.json`, just like how other model types in candle already do (see the bert.rs file for example).

Allow marian configs to deserialize from json.

---

candle-examples/examples/stella-en-v5/README.md
candle-examples/examples/stella-en-v5/main.rs
candle-transformers/src/models/mod.rs
candle-transformers/src/models/stella_en_v5.rs

`Stella_en_1.5B_v5` is a top ranking model (top 5) in Retrieval and Reranking tasks as of 8th October 2024. 
[Model Card](https://huggingface.co/dunzhang/stella_en_1.5B_v5)
This PR adds support for the model along with some examples.
`Stella_400M` seems to follow a significantly different implementation. Have not implemented it in this PR.
Closes #2525

Adds support for Stella_en_v5 embedding model - 1.5B variant

---

candle-transformers/src/models/llama.rs

Use the fused version of softmax (`softmax_last_dim`) in the Llama attention layer. 
Modest improvement on the example (A100-SXM4-80GB): 
Before: 
```
$ cargo run -F cuda --example llama -- --which v31-instruct -n 100
loading the model weights from meta-llama/Meta-Llama-3.1-8B-Instruct
starting the inference loop
My favorite theorem is 2+2=4
This joke is most likely to be appreciated by children who love mathematics. The theorem in question, of course, is not the usual way that mathematicians would think about it. This response shows a lack of understanding of what a mathematical theorem actually is.
Why do chemists shun parties? Because they fear cheesing off their friends.
A joke about why chemists are reluctant socializers. Although this joke is amusing and somewhat related to …
```

Use fused softmax kernel in llama attention layer

---

candle-examples/examples/stable-diffusion-3/clip.rs
candle-examples/examples/stable-diffusion-3/main.rs
candle-examples/examples/stable-diffusion-3/sampling.rs
candle-transformers/src/models/mmdit/model.rs
candle-transformers/src/models/mmdit/projections.rs

Image generated with 3.5 turbo.

Stable diffusion 3.5 support.

---

Cargo.toml
candle-core/Cargo.toml
candle-core/src/cuda_backend/device.rs
candle-core/src/custom_op.rs
candle-core/src/device.rs
candle-core/src/error.rs
candle-core/src/lib.rs
candle-core/tests/custom_op_tests.rs

This adds some preliminary support for kernels implemented using UG, this will allow for easy fusion of kernels. Only cuda is supported in this PR, the metal backend hasn't been activated yet.

Support for UG kernels.

---

candle-examples/examples/stable-diffusion-3/main.rs
candle-examples/examples/stable-diffusion-3/sampling.rs
candle-transformers/src/models/mmdit/model.rs

This closes #2588 .
I noticed SLG doesn't perform well when number of inference steps is low. So, below is a comparison with `--num-inference-steps=50`.
|  w/o SLG | w/ SLG |
| ---- | ---- |
|![out-50-no-slg](https://github.com/user-attachments/assets/25079a16-b96b-417f-9e5b-74269d3ef278)|![out-50-slg](https://github.com/user-attachments/assets/ce0723c3-f3aa-4867-b928-bf6205b3125c)|
Appearantly the fingers look better. This could be an evidance that supports claimed benefits (improved anatomy). But other aspects of the image changes, too. 
The SLG parameter is copied from that in SD3 reference design, which is originally with dpmpp_2m sampler (not Euler sampler in the Candle example here). So, it might be worth to tweak the parameters with more experiments.

Support Skip Layer Guidance (SLG) for Stable Diffusion 3.5 Medium

---

.vscode/settings.json
candle-core/src/layout.rs
candle-core/src/shape.rs
candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/scaled_dot_product_attention.metal
candle-nn/src/ops.rs
candle-nn/tests/sdpa.rs
candle-transformers/src/models/quantized_llama.rs

This PR adds some MLX SDPA kernels on Metal.
I can observe about a 26% performance improvement with Llama 3.1 8b @ q4k and @ q8_0 when testing through mistral.rs on my Candle fork. I updated the quantized_llama.rs file here to use the new function.
This PR adds a function `candle_nn::ops::sdpa`. The MLX attention kernels don't support masking yet, so the performance gains are only for decoding on Metal. Once/if they do, I'll update them - otherwise we can explore using Flash Attention kernels for Metal from llama.cpp.

Add some fast Metal MLX SDPA kernels 

---

candle-core/src/backend.rs
candle-core/src/backprop.rs
candle-core/src/conv.rs
candle-core/src/cpu/mod.rs
candle-core/src/cpu_backend/mod.rs
candle-core/src/cuda_backend/mod.rs
candle-core/src/device.rs
candle-core/src/display.rs
candle-core/src/dummy_cuda_backend.rs
candle-core/src/error.rs
candle-core/src/layout.rs
candle-core/src/lib.rs
candle-core/src/metal_backend/mod.rs
candle-core/src/op.rs
candle-core/src/pickle.rs
candle-core/src/quantized/ggml_file.rs
candle-core/src/quantized/gguf_file.rs
candle-core/src/quantized/mod.rs
candle-core/src/safetensors.rs
candle-core/src/scalar.rs
candle-core/src/streaming.rs
candle-core/src/utils.rs
candle-transformers/src/generation/mod.rs
candle-transformers/src/object_detection.rs
candle-transformers/src/quantized_nn.rs
candle-transformers/src/quantized_var_builder.rs
candle-transformers/src/utils.rs

- More model docs for candle_transformers
- add set of module docs in candle_core to fill out the docs page.

20241118 docs

---

candle-core/src/tensor.rs

The doc string for `zeros_like` mistakenly says that the resulting `Tensor` will be filled with "ones" as opposed to "zeros".

[chore] Fix small typo in doc string of `Tensor::zeros_like`

---

candle-nn/src/var_builder.rs

- discussed in a Discord Thread
- added a method to allow loading of pth files that have a state_map.

Provide a method to allow PTH files with state maps to be loaded.

---

candle-examples/examples/whisper-microphone/main.rs

At least on my macOS Sequoia system (MBP 14" 2021, M1 Pro), when I run the `whisper-microphone` example after it has gathered 10 seconds of audio, it fails before the transcription:
```
Error: Insufficient buffer size 384 for input channel 0, expected 1024
```
At least for the audio device I'm using (Airpods Pro Max), there is no guarantee that each audio buffer is a multiple of 1024 samples.  Thus at the end of the 10 seconds, `buffered_pcm` can have some samples at the end that do not form a complete 1024 sample chunk.
This fixes that by tracking when there is a partial chunk at the end of the buffer, and leaving it in `buffered_pcm` to be processed on the next loop iteration.
Note that, in the interest of keeping this PR as small as possible, I didn't make any other changes to this …

Fix for whisper-microphone example failure if audio isn't chunk aligned

---

candle-core/src/metal_backend/mod.rs
candle-metal-kernels/src/indexing.metal

- Add a U32 gather.
- the whitespace changes were editor autoformat

add u32 - U32 gather

---

candle-examples/examples/nvembed_v2/README.md
candle-examples/examples/nvembed_v2/main.rs
candle-transformers/src/models/mod.rs
candle-transformers/src/models/nvembed_v2/decoder.rs
candle-transformers/src/models/nvembed_v2/embedding.rs
candle-transformers/src/models/nvembed_v2/mod.rs
candle-transformers/src/models/nvembed_v2/model.rs

[NV-Embed-v2](https://huggingface.co/nvidia/NV-Embed-v2) is a text embedding model that ranks No. 1 (as of Nov 25 2024) on the [MTEB](https://huggingface.co/spaces/mteb/leaderboard) benchmark.
This implementation reproduces the example in the [model card](https://huggingface.co/nvidia/NV-Embed-v2).
License: CC-BY-NC-4.0
Please let me know if any changes are required!

Add Nvembed v2 model

---

candle-examples/examples/depth_anything_v2/main.rs
candle-transformers/src/models/depth_anything_v2.rs

This pull request includes changes to the `candle-examples` and `candle-transformers` projects to improve memory management and simplify the codebase. The most important changes involve the use of `Arc` for shared ownership and the removal of lifetime parameters in the `DepthAnythingV2` and `DPTHead` structures.
Improvements to memory management:
* [`candle-examples/examples/depth_anything_v2/main.rs`](diffhunk://#diff-dabf4ef2a3af13ca0e446f92581a93bb7fcffd8823842ec09dd5861597054a92L85-R83): Updated the `DepthAnythingV2::new` function call to use `Arc` for shared ownership of `dinov2`.
* [`candle-transformers/src/models/depth_anything_v2.rs`](diffhunk://#diff-ff06aaddee74b48513516bffd4454117dbfa684ba95f900b120f5d2b8ed2cccaL518-R542): Added `Arc` to the `DepthAnythingV2` struct to manage …

make DepthAnythingV2 more reusable

---

candle-transformers/src/models/pixtral/vision_model.rs

For Pixtral models, the position encodings are resampled on-the-fly when dealing with images which are smaller than the default model's config (1024x1024px images, or 64x64 patches of size 16px x 16px). Doing so seems to slightly improve generations (in particular when it comes to the number of objects).
* [link](https://github.com/huggingface/transformers/blob/05260a1fc1c8571a2b421ce72b680d5f1bc3e5a4/src/transformers/models/pixtral/modeling_pixtral.py#L501) to ref in Huggingface code
* [testing the fix](https://gist.github.com/ameroyer/fb565b817291e0e848a6d920ff93b8fc) : mainly looking at the model outputs for different image size

Fix position encodings for Pixtral

---

candle-datasets/src/batcher.rs

Fix Batcher iterator break when return_last_incomplete_batch and items.is_empty (#2654)

Fix Batcher iterator break condition

---

candle-transformers/src/models/whisper/audio.rs

- due to num_threads going to zero in single threaded case

Fix bug in whisper transformer

---

candle-examples/examples/xlm-roberta/Readme.md
candle-examples/examples/xlm-roberta/main.rs
candle-transformers/src/models/mod.rs
candle-transformers/src/models/xlm_roberta.rs

Some of the good reranker models are based on this architecture and I think its a good addition to the current repository of models. 
The architecture is not very different than Bert but the position embedding technique is a bit different.

Added XLMRobertaModel for Reranking

---

candle-examples/examples/stable-diffusion/main.rs
candle-transformers/src/models/stable_diffusion/ddim.rs
candle-transformers/src/models/stable_diffusion/euler_ancestral_discrete.rs
candle-transformers/src/models/stable_diffusion/mod.rs
candle-transformers/src/models/stable_diffusion/schedulers.rs
candle-transformers/src/models/stable_diffusion/uni_pc.rs

Hi, thanks for the awesome library! It's great having these tools available in the Rust ecosystem.
I was interested in low step-count inference for some experiments, so ported over the [UniPC](https://arxiv.org/abs/2302.04867) scheduler. I figured I'd open a PR here in case this work is useful to others. Here is a comparison with Euler A and DDIM at 5 steps which demonstrates UniPC's benefits for quick convergence:

UniPC for diffusion sampling

---

candle-transformers/src/models/mistral.rs

This PR fixes Mistral attention on Metal device.
Before fix:
```
Metal(KernelError(MatMulNonContiguous { lhs_stride: [64, 4, 2, 1], rhs_stride: [2048, 64, 1024, 1], mnk: (2, 64, 2) }))
```

Fix mistral attention on Metal

---

README.md

I was wondering if we could add a link to a project that I've been working on as of late where I translate the PyTorch code in Sebastian Raschka's Build an LLM from Scratch book into Rust/Candle.
I think it could be useful to users who want to learn Candle by following along with Sebastian's really incredible text.

Add link to `llms-from-scratch-rs` in README

---

candle-examples/examples/modernbert/README.md
candle-examples/examples/modernbert/main.rs
candle-nn/src/layer_norm.rs
candle-nn/src/lib.rs
candle-transformers/src/models/mod.rs
candle-transformers/src/models/modernbert.rs

Model and basic fill-mask example as in the Huggingface Transformers model card.

ModernBERT model

---

candle-metal-kernels/src/lib.rs
candle-metal-kernels/src/scaled_dot_product_attention.metal
candle-nn/src/ops.rs

This PR:
- Adds the 2-pass vector SDPA inference kernel (https://github.com/ml-explore/mlx/pull/1597) - useful for long-context generation
- Syncs the recent addition of masking to the SDPA vector kernels (https://github.com/ml-explore/mlx/pull/1757)
- I'm not sure how useful this change is as we do not use a mask during the decoding phase when these kernels are used (q_seq = 1, kv_seq > 1). However, I think keeping the kernels in-sync with upstream will be helpful.

Sync upstream MLX sdpa vector kernels with mask

---

candle-book/Cargo.toml
candle-examples/Cargo.toml
candle-examples/examples/glm4/main.rs
candle-examples/src/lib.rs
candle-transformers/src/models/glm4.rs

This PR primarily addresses the generation issue in GLM4, specifically the missing `rope_ratio` in the construction of the cosine-sine cache. Additionally, it enables the configuration to be loaded from a JSON file and allows weights to be loaded from a local path, facilitated by a new utility function named `hub_load_local_safetensors`. Furthermore, it resolves a compilation issue caused by the updated `hf-hub` crate in the previous #2691, which now depends on a newer version of the `tokio` package.
Tested case: 
```shell
cargo run --release --example glm4 --features cuda -- --weight-path /home/weights/glm-4-9b-chat/ --prompt "Please talk about deep learning."
```
It now generates better answers (align with the official results).

Fix GLM4 alignment issue

---

candle-flash-attn/build.rs

As reported here, build on Windows (msvc)  requires `-D_USE_MATH_DEFINES"`
https://github.com/EricLBuehler/mistral.rs/issues/941

Fix candle-flash-attn build on Windows (msvc)

---

candle-examples/examples/stable-diffusion/main.rs

This change updates the stable diffusion example with inpainting for 1.5, 2 and XL. It adds a --mask-path command line argument to set the path to the mask image and it uses the existing img2img argument to set the input image.
The following is an example of the output of 10 samples from SDXL using:
```
cargo run --example stable-diffusion --features cuda,cudnn,flash-attn -- --prompt "a cute baby lion sitting on a park bench" --sd-version xl-inpaint --use-f16 --use-flash-attn --img2img overture-creations-5sI6fQgYIuo_big.png --mask-path overture-creations-5sI6fQgYIuo_mask_big.png --guidance-scale 7 --num-samples 10
```

Add inpainting to the stable diffusion example

---

candle-nn/Cargo.toml
candle-nn/tests/sdpa.rs

This avoids some spurious failures caused by the tolerances.

Make the metal sdpa tests deterministic.

---

candle-examples/examples/moondream/main.rs

`moondream` example seems to be broken now.
The revision in repo fails to load.
```
Error: path: "../models--vikhyatk--moondream2/snapshots/30c7cdf3fa6914f50bee3956694374143f5cc884/model.safetensors" MetadataIncompleteBuffer
```
I think upstream may have broken it.
Changing it to the latest revision of  `vikhyatk/moondream1` fixes the example.
Quantized version works just fine.

use moondream1 model/revision for moondream example

---

candle-examples/examples/debertav2/README.md
candle-examples/examples/debertav2/main.rs
candle-transformers/src/models/debertav2.rs
candle-transformers/src/models/mod.rs

This adds Microsoft's Deberta V2 and V3 model into the `candle` ecosystem. It also includes an example file demonstrating how to use it, as well as a README for more information.
At the time of this commit, the model can only do Named Entity Recognition and Text Classification. There are other modes such as Question Answering, Multiple Choice and Masked Input that could still be developed for this at a later point in time.

Adds DebertaV2/V3

---

candle-core/Cargo.toml
candle-core/src/cuda_backend/device.rs
candle-core/src/custom_op.rs
candle-core/src/error.rs
candle-core/src/metal_backend/device.rs

So that wasm32 can compile
fixes: https://github.com/huggingface/candle/issues/2736

fix: place `ug` dep behind `not wasm32` flag

---

candle-examples/examples/siglip/main.rs
candle-transformers/src/models/siglip.rs

Adding interpolated/dynamic position encodings to Siglip, similar to how it's done in Dino (although simpler because Siglip doesn't have a class token)
Roughly follows the [equivalent in HF transformers](https://github.com/huggingface/transformers/pull/30719) but with a simpler interpolation
```bash
RUST_BACKTRACE=1 NVCC_CCBIN=/usr/bin/gcc cargo run --features cuda --example siglip -- --image-size 448
```
**before:**
(when trying to add position encodings to tokens)
```
Error: shape mismatch in broadcast_add, lhs: [2, 784, 768], rhs: [196, 768] 
```
**after:**
```
Interpolating position embeddings to (28, 28)
softmax_image_vec: [1.9005219e-14, 1.0336038e-13, 1.0, 0.9999999, 6.7562546e-8, 1.344231e-11]
Results for image: candle-examples/examples/stable-diffusion/assets/stable-diffusion-xl.j …
```

add dynamic position encoding to Siglip

---

Cargo.toml

The following executed with zero failures
```shell
cargo test --features cuda,cudnn,cudarc  1172.67s user 427.15s system 1468% cpu 1:48.93 total
```

update to cudarc to v0.13.5 to support cuda 12.8

---

candle-core/src/shape.rs

I noticed that the From<Tuple> implementations were quite repetitive and could be refactored using macros. I also noticed there were no tests for them so I added a few basic tests. I see other things which could be refactored using macros but I will create different PRs for them.

Refactor Shape From<Tuple> implementations by using macros, add tests

---

candle-core/src/backprop.rs

While debugging backpropagation path of a Tensor, I would need to look at the nodes of it. But `sorted_nodes` is not public function for now. This patch makes it a public function for easy debugging.

Make sorted_nodes pub function

---

candle-examples/examples/whisper/main.rs

```
error[E0432]: unresolved import `rand::distributions`
--> candle-examples/examples/whisper/main.rs:17:12
|
17 | use rand::{distributions::Distribution, SeedableRng};
|            ^^^^^^^^^^^^^ could not find `distributions` in `rand`
error[E0433]: failed to resolve: could not find `distributions` in `rand`
--> candle-examples/examples/whisper/main.rs:211:35
|
211 |                 let distr = rand::distributions::WeightedIndex::new(&logits_v)?;
|                                   ^^^^^^^^^^^^^ could not find `distributions` in `rand`
|
help: consider importing this struct
|
12  + use rand::distr::weighted::WeightedIndex;
|
help: if you import `WeightedIndex`, refer to it directly
|
211 -                 let distr = rand::distributions::WeightedIndex::new(&logits_v)?;
211 + …
```

Fix for whisper example. rand::distribution is now rand::distr

---

candle-core/src/pickle.rs

Added Long1 Opcode, required for pulling tensors with offset or size > 32-bit maximum
Fixed tensor offset calculation, which has to be scaled by the data width.

Pickle decoder fix and Long1 opcode addition.

---

candle-examples/examples/mnist-training/main.rs

this commit just adds `use rand::rng` to the top of the `mnist-training` example and replaces `thread_rng`(deprecated) function with `rng` in the file.

Fixed rand import for mnist-training

---

candle-core/benches/benchmarks/mod.rs
candle-core/src/cuda_backend/mod.rs

Allows borrowing a mutable cuda slice from `CudaStorage`, which is necessary for performing in-place operations safely.

Add as_cuda_slice_mut to CudaDType and CudaStorage

---

candle-transformers/src/models/bert.rs
candle-transformers/src/models/chinese_clip/text_model.rs

This PR addresses a critical issue with dtype compatibility in the BERT implementation. Previously, the attention mask was hardcoded to use DType::F32, which caused dtype mismatch errors when using models with different precision types (such as BF16 causing Error: dtype mismatch in mul, lhs: BF16, rhs: F32)
Changes:
Modified the get_extended_attention_mask function to convert the f32::MIN tensor to the same dtype as the attention mask
Updated BertModel::forward to use the model's dtype (obtained from embedding_output) instead of hardcoding DType::F32
This change ensures that the attention mask uses the same dtype as the model weights, preventing errors when using non-F32 precision types like BF16.

Fix dtype mismatch in BERT attention mask handling

---

candle-examples/examples/quantized-gemma/main.rs
candle-transformers/src/models/quantized_gemma3.rs

- Scaled down RoPE base frequency by the scale_factor in the GGUF.
- Fixed the chat prompt
#2891

fixed quantized-gemma example

---

candle-examples/examples/gemma/main.rs
candle-transformers/src/models/gemma3.rs

- In transformers: Made RoPE frequency change based on the layer like the transformers implementation [here](https://github.com/huggingface/transformers/blob/b6d65e40b256d98d9621707762b94bc8ad83b7a7/src/transformers/models/gemma3/modular_gemma3.py#L511) and [here](https://github.com/huggingface/transformers/blob/b6d65e40b256d98d9621707762b94bc8ad83b7a7/src/transformers/models/gemma3/modular_gemma3.py#L375C80-L376C1)
- Gemma3 uses a 5:1 sliding to non-sliding attention layer ratio ([source](https://arxiv.org/html/2503.19786v1#S2)). 
- In example: Changed prompt format to [Official Recommended Inference Settings](https://docs.unsloth.ai/basics/tutorial-how-to-run-and-fine-tune-gemma-3#official-recommended-inference-settings) for Gemma3 Instruct 
- In example: Changed eos token from `<eos>` …

Fixed Gemma3 model and example

---

candle-core/benches/bench_main.rs
candle-core/benches/benchmarks/copy.rs
candle-core/benches/benchmarks/mod.rs
candle-core/src/device.rs
candle-core/tests/tensor_tests.rs

This reduces the set of types on which `Tensor::new` can be called, e.g. `Vec<Vec<&[T]>>` is not supported anymore.
The main upside is that it improves performance a lot. I've added a benchmark that is similar to the copy of an attention mask that we ran in our model inference setup. On a ryzen 7950x with a single core I go from ~150MB/s to ~2.1GB/s (which is still quite far from the specs bandwidth).
_edit_: With further changes the benchmark now runs at 13GB/s, still a bit low compared to the specs.

Optimize Tensor::new when called on nested Vec<..>.

---

candle-transformers/src/models/quantized_qwen3.rs

This PR optimizes the KV cache implementation in the quantized Qwen3 model by adopting the same approach used in Qwen2. The changes address the OOM issue reported in #2950.
- Replaced the `KvCache` type with `Option<(Tensor, Tensor)>` for more efficient memory management
- Removed dependency on `candle_nn::kv_cache::KvCache`
- Simplified cache initialization and reset logic
- Implemented direct tensor concatenation for cache updates
Implementation based on the KV cache approach in quantized Qwen2 model

Fixed Quantized Qwen3 Model

---

candle-transformers/src/models/quantized_qwen3.rs

Further optimize Qwen3 KvCache as discussed in PR #2951 by making the tensors contiguous before the `repeat_kv` calls. Two times speedup on autoregressive inference in my tests (rtx3090, qwen3:32b). Thanks @LaurentMazare for coming up with the fix.

Optimize Quantized Qwen3 KvCache 

---

candle-examples/examples/quantized-qwen2-instruct/README.md
candle-examples/examples/quantized-qwen3/README.md

- Fixed wrong usage in README.md of quantized-qwen3 and quantized-qwen2-instruct
Issue #2949 
Those two models' example works with parameter `which` not `model`.
I added additional example of using different size of model and replaced `model` with `which`
@LaurentMazare 
Could you review these changes?

Fix docs quantized qwen3

---

candle-examples/examples/phi/main.rs
candle-transformers/src/models/phi3.rs

Add support for the different bits used in phi-4 mini:
- Longrope (entirely pre-computed for now).
- `tie_word_embeddings`.
- `partial_rotaryfactor`.

Proper support for phi-4

---

candle-core/src/indexer.rs

Fix the doc test for `indexer#i(&self, (a b):(A, B))`

(hotfix) fix the doc test for indexer#i(&self, (a b):(A, B))

---

candle-examples/Cargo.toml
candle-examples/examples/onnx-llm/README.md
candle-examples/examples/onnx-llm/main.rs
candle-onnx/src/eval.rs
candle-onnx/tests/ops.rs

Added more onnx ops and the ability to run [SmolLM-135M](https://huggingface.co/HuggingFaceTB/SmolLM-135M) example.
- Added [ScatterND](https://github.com/onnx/onnx/blob/main/docs/Operators.md#scatternd) and [Trilu](https://github.com/onnx/onnx/blob/main/docs/Operators.md#trilu) Onnx ops.
- Added Tests for ScatterND and Trilu onnx ops.
- Added new example `onnx-llm`.

candle-onnx: Implement Trilu and ScatterND ops

---

candle-transformers/src/models/qwen3.rs

Instead of initializing the `KvCache` with the full position embedding length, initialize it with 512, similar to what is done in the quantized version [here](https://github.com/huggingface/candle/blob/0224a749f0b2082f19831256ced6afe284c56457/candle-transformers/src/models/quantized_qwen3.rs#L163-L165) This resolves large memory allocation issues.

Fix cuda memory error for Qwen3 non-quantized

---

candle-transformers/src/models/dac.rs
candle-transformers/src/models/parler_tts.rs

The [descript audio codec](https://github.com/descriptinc/descript-audio-codec) (DAC) model is not prefixed with `model`, so when you try and load it you get the following error:
```
cannot find tensor model.encoder.block.0.weight_g
```
This change fixes compatibility with the provided model.
Excerpt from the `state_dict` of the released model https://github.com/descriptinc/descript-audio-codec/releases/tag/1.0.0
```
decoder.model.0.bias
decoder.model.0.weight_g
decoder.model.0.weight_v
decoder.model.1.block.0.alpha
decoder.model.1.block.1.bias
decoder.model.1.block.1.weight_g
decoder.model.1.block.1.weight_v
```

fix: DAC model prefix

---

README.md

Uses [this repo / badge tool](https://github.com/gitlimes/dcbadge) instead.

Fix Discord badge

---

candle-core/src/safetensors.rs

Hi,
I have a small ML-enabled [app](https://www.voegele.me/posts/suppalist/) that uses candle with wasm under the hood. Downloading the model takes a long time so I quantized it to 8-bit integers. Candle doesn't have an I8 `DType` and the safetensors load doesn't support I8.
This PR adds the ability to load a safetensors file with I8 by upcasting it to I64, similar to the existing I32 to I64 conversion.
Based on this [PR](https://github.com/huggingface/candle/pull/2432) for adding a `DType::I32`, I skipped adding a `DType::I8` for now, but would consider that if requested.
Thanks!

Load safetensors with i8

---

candle-core/src/layout.rs
candle-core/src/quantized/mod.rs
candle-core/src/safetensors.rs
candle-core/src/tensor.rs
candle-examples/examples/chinese_clip/main.rs
candle-examples/examples/clip/main.rs
candle-examples/examples/distilbert/main.rs
candle-examples/examples/mobileclip/main.rs
candle-examples/examples/segformer/main.rs
candle-examples/examples/siglip/main.rs
candle-examples/examples/yolo-v3/darknet.rs
candle-pyo3/src/lib.rs
candle-transformers/src/models/encodec.rs
candle-transformers/src/models/xlm_roberta.rs
candle-wasm-examples/llama2-c/src/worker.rs

The new clippy rules are stricter about:
[mismatched-lifetime-syntaxes](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/lifetime_syntax/static.MISMATCHED_LIFETIME_SYNTAXES.html)
[unnecessary_unwrap](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap)
[cloned_ref_to_slice_refs](https://rust-lang.github.io/rust-clippy/master/index.html#cloned_ref_to_slice_refs)

Fix Clippy for CI

---

candle-examples/examples/stable-diffusion/main.rs

Running the stable diffusion example with Metal results in an error with the seed (possibly) being out of range.
```
$ cargo run --example stable-diffusion --release --features=metal -- --prompt "a cosmonaut on a horse (hd, realistic, high-def)" --sd-version turbo
Compiling candle-transformers v0.9.1 (/Users/kylekelley/code/src/github.com/huggingface/candle/candle-transformers)
Compiling candle-examples v0.9.1 (/Users/kylekelley/code/src/github.com/huggingface/candle/candle-examples)
Finished `release` profile [optimized] target(s) in 13.34s
Running `target/release/examples/stable-diffusion --prompt 'a cosmonaut on a horse (hd, realistic, high-def)' --sd-version turbo`
Using seed 14094623835642992148
Error: Metal error Metal seed must be less than or equal to u32::MAX
Caused by:
Metal …
```

pick seed <= u32::MAX when using metal

---

candle-nn/Cargo.toml
candle-nn/src/cpu_flash_attention.rs
candle-nn/src/lib.rs
candle-nn/tests/cpu_flash_attn.rs

This introduces fused CPU attention kernels for optimized CPU inference. This removes the necessity to materialize the attention matrices, thereby dramatically improving throughput.
On an M3 Max with Llama 3.2 3b at 4-bit quantization, I am measuring a **_4x_ increase** in decode T/s. This is faster than llama.cpp, even with llama.cpp CPU FlashAttention enabled.
These kernels are loosely based on the work in FlashAttention and CPU implementations in vLLM and ggml, but have been modified for higher performance.
<details>
<summary>Algorithm</summary>
1. **Choose execution path**  
- **Decode path**: if the query length `S_q == 1`, invoke a specialized “single-Q” routine  
- **Batched path**: otherwise, invoke the general batched attention routine
2. **Compute attention**  
- **Parallel …

Fused CPU attention kernels (~4x performance increase)

---

candle-core/Cargo.toml
candle-core/src/cuda_backend/device.rs
candle-core/src/custom_op.rs
candle-core/src/error.rs
candle-core/src/metal_backend/device.rs

From #2749, when uploading to app store some users get an error:
> ITMS-90755: Invalid Binary - The following binaries in your app contains prohibited instructions: (my binary with candle in it). Remove the instructions from the binaries, rebuild and resubmit.
This seems to be because the `ug` crate uses `gemm` ops that are unsupported on iOS. This PR hides any `ug` functionality behind a cfg flag similar to `wasm`.

Fix iOS app store validation issues

---

candle-transformers/src/models/quantized_phi3.rs

The current implementation of the quantized_phi3 model does not clear its kv cache between distinct prompts. This leads to errors when attempting to generate text sequentially with the same model instance.
If you try to prompt the model more than once you get an shape error like this:
`
cannot broadcast [12, 12] to [1, 40, 12, 124]
`
I double checked quantized gemma3 to make sure that you guys do usually clear the cache and you did, so I went ahead and figured out how to make the fix, it's just a few lines of code to use the .reset method on the KvCache when pos is 0. I already tested it locally and it seems that I have no issues sending multiple prompts sequentially to phi3/phi4 now :)

fix kv cache issue with quantized_phi3 implementation

---

Cargo.toml

ug 0.5.0 pulls in cudarc 0.17.3, which supports CUDA 13
Extension of https://github.com/huggingface/candle/pull/3078

Upgrade ug dependency for CUDA 13 support

---

candle-metal-kernels/src/metal/command_buffer.rs
candle-metal-kernels/src/metal/commands.rs

Hide the `ThreadId` usage inside `CommandBufferThreadMap`.
Remove some failure points from `wait_until_completed`.

[Metal] Improve command buffer map

---

Cargo.toml

`ug` uses `gemm 0.18`, while `candle-core` and `candle-nn` still depend on `gemm 0.17`.
This causes for 2 `gemm` versions to be compiled currently (visible in `Cargo.lock`).
This PR bumps candle's dependency on `gemm` to `0.18.2`, resulting in just one `gemm` dependency.
I ran the benches on my local machine, the changes are within noise threshold mostly, no big gains or losses.

bump gemm dependency to 0.18.2 to match ug

---

candle-transformers/src/models/stable_diffusion/mod.rs

Add build_unet_sharded method to StableDiffusionConfig to support loading UNet models from multiple sharded safetensors files. This is necessary for large models that are distributed across multiple files to avoid memory constraints during model storage and distribution.
The new method accepts a slice of file paths instead of a single directory, allowing direct specification of shard files. It uses mmaped_safetensors for efficient memory usage when loading from multiple weight files.
Key differences from build_unet:
- Accepts &[P] where P: AsRef<Path> for multiple file paths
- Uses from_mmaped_safetensors with file list instead of directory
- Maintains same signature for in_channels, use_flash_attn, and dtype
Use case: Loading models like FLUX or large SD3.5 variants that are distributed …

feat(stable-diffusion): add build_unet_sharded method 
