huggingface/candle

- Cargo.toml
- examples/basics.rs
- examples/cuda_basics.rs
- src/cuda_backend.rs
- src/device.rs
- src/dummy_cuda_backend.rs
- src/error.rs
- src/lib.rs
- src/shape.rs
- src/storage.rs
- src/tensor.rs
- tests/grad_tests.rs
- tests/tensor_tests.rs
Add some preliminary support for cuda devices, this only includes the affine kernel for the contiguous case.
> Add Cuda support.

- .github/workflows/rust-ci.yml
- Cargo.toml
- kernels/src/affine.cu
- kernels/src/embeddings.cu
- kernels/src/reduce.cu
- kernels/src/ternary.cu
- src/cpu_backend.rs
- src/cuda_backend.rs
- src/dtype.rs
- src/npy.rs
- src/op.rs
This doesn't include the bf16 kernels though.
> Add support for f16 and bf16

- Makefile
- candle-core/src/cuda_backend.rs
- candle-kernels/src/ternary.cu
Also move the makefile back to the toplevel + adapt it to the new structure.
> Fix two cuda bugs (matmul and where_cond).

- README.md
- candle-core/src/cuda_backend.rs
- candle-core/tests/tensor_tests.rs
And fix some bugs in narrow & cat on the cuda side thanks to the tests.
> Run the tensor tests for the cuda backend too.

- candle-core/tests/tensor_tests.rs
- candle-core/tests/test_utils.rs
And enable the softmax test on gpu using some tolerance.
> Add some test utils module.

- candle-core/examples/llama/main.rs
This required a bit of fiddling around the pose embeddings as well as storing all the sequence in the cache.
> Enable the KV cache

- candle-kernels/src/affine.cu
- candle-kernels/src/binary.cu
- candle-kernels/src/cast.cu
- candle-kernels/src/compatibility.cuh
- candle-kernels/src/cuda_utils.cuh
- candle-kernels/src/embeddings.cu
- candle-kernels/src/reduce.cu
- candle-kernels/src/ternary.cu
- candle-kernels/src/unary.cu
This seems to require compute_cap >= 8.0.0 so conditioning with this.
> Support for bf16 in cuda kernels

- candle-core/src/cpu_backend.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/display.rs
- candle-core/src/dtype.rs
- candle-core/src/npy.rs
- candle-core/src/op.rs
- candle-kernels/src/affine.cu
- candle-kernels/src/binary.cu
- candle-kernels/src/cast.cu
- candle-kernels/src/embeddings.cu
- candle-kernels/src/ternary.cu
The main motivation is to use this as a bool tensor for things like `where` and for the upcoming comparison operators.
> Add support for u8

- candle-core/examples/llama/var_store.rs
- candle-core/examples/llama/weights.rs
Also cleanup the npy var-builder mess.
> Early conversion for the llama weights.

- .gitignore
- Cargo.toml
- candle-pyo3/Cargo.toml
- candle-pyo3/README.md
- candle-pyo3/src/lib.rs
- candle-pyo3/test.py
This adds some very simple pyo3 wrappers, most ops are not exposed at the moment.
> Preliminary python api via pyo3

- candle-kernels/build.rs
- rerun-if-change:src/ encapsulates any src modification (including file
additions).
- Now not rewriting `src/lib.rs` everytime (it triggers new builds.)
- Also using modified timestamp to trigger kernel recompilation (should
prevent skipping modified source files).
- Will also rewrite when a kernel is removed.
> Fixing the cached build.

- candle-core/src/cpu_backend.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/error.rs
- candle-examples/examples/llama/main.rs
- Use f16 in llama when mkl is not set.
- Avoid the dependency to cuda when using mkl.
- Minor tweaks.
> MKL adjustments.

- candle-examples/examples/bert/main.rs
- The tokenizer doesn't have a padding so we need to set it.
- The name of the weights are different.
> Enabling `roberta` for the example (it's the same model as Bert, with just different naming.)

- candle-examples/examples/falcon/model.rs
After this, prediction seem to line up with the python version.
> Add the call to dense in the attention layer.

- candle-kernels/src/unary.cu
Some how I forgot to push this file in the previous PR.
> Add the elu cuda kernel.

- candle-core/Cargo.toml
- candle-core/src/cpu_backend.rs
- candle-core/src/lib.rs
- candle-core/src/mkl.rs
This is pretty straightforwrard as we only use 3 functions from mkl for matmul.
> Remove the dependency to blas and use mkl directly.

- candle-nn/src/init.rs
- candle-nn/src/lib.rs
Support initialization modes similar to PyTorch so that they are easy to integrate in the different nn layers with expected similar behavior (though having the exact same behavior as the PyTorch implementation for the same seed is not expected).
> Add a tensor initialization module.

- candle-core/src/backend.rs
- candle-core/src/conv.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/device.rs
- candle-core/src/dummy_cuda_backend.rs
- candle-core/src/error.rs
- candle-core/src/lib.rs
- candle-core/src/storage.rs
- candle-core/src/tensor.rs
Add some backend traits so as to make backends more modular (maybe using some dynamic dispatch at some point) and to formalize the interface that they should implement.
> Modular backends

- candle-core/src/indexer.rs
- candle-examples/examples/llama/main.rs
- candle-examples/examples/llama/model.rs
- Add a batch dimension to llama, so that some of the inference code can be shared with falcon.
- Fix an issue with the indexer.
- Use the `nn::Embedding` layer.
> Llama batch

- candle-core/src/convert.rs
- candle-core/src/lib.rs
- candle-core/src/variable.rs
- candle-nn/src/lib.rs
- candle-nn/src/optim.rs
- candle-nn/tests/optim.rs
The api is close to the PyTorch one, specifying an optimizer struct that holds some parameters and has some `step` function to adjust the parameters based on the gradients.
> Add the SGD optimizer

- Cargo.toml
- README.md
- candle-core/Cargo.toml
- candle-core/src/cuda_backend.rs
- candle-core/src/dummy_cuda_backend.rs
- candle-examples/Cargo.toml
- candle-examples/examples/bert/main.rs
- candle-examples/examples/falcon/main.rs
- candle-examples/examples/llama/main.rs
- candle-examples/examples/musicgen/main.rs
- candle-examples/examples/whisper/main.rs
- candle-nn/Cargo.toml
- candle-pyo3/Cargo.toml
- candle-transformers/Cargo.toml
- candle-wasm-example/Cargo.toml
Seems very important for a lot of exploring users usually on laptop
without GPUs.
Adding more README instructions in a follow up.
> Removing cuda default.

- candle-core/src/cpu_backend.rs
- candle-core/src/layout.rs
- candle-core/src/lib.rs
- candle-core/src/strided_index.rs
When broadcasting on the cpu, handle separately the case with left-broadcast + contiguous + right-broadcast.
> Broadcasting performance optimization (cpu)

- candle-core/src/cpu_backend.rs
- candle-core/src/shape.rs
- candle-examples/examples/bert/model.rs
Also tweak the vectorised unary op implementation to be used in block mode.
> Add Shape try into

- candle-core/src/backend.rs
- candle-core/src/backprop.rs
- candle-core/src/cpu_backend.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/dummy_cuda_backend.rs
- candle-core/src/op.rs
- candle-core/src/storage.rs
- candle-core/src/tensor.rs
- candle-examples/examples/simple-training/main.rs
Same semantics as in PyTorch ([doc](https://pytorch.org/docs/stable/generated/torch.gather.html#torch.gather)).
> Add the gather op.

- candle-core/src/cuda_backend.rs
- candle-examples/Cargo.toml
- candle-examples/build.rs
- candle-examples/examples/custom-ops/cuda_kernels.rs
- candle-examples/examples/custom-ops/kernels/layernorm_kernels.cu
- candle-examples/examples/custom-ops/kernels/reduction_utils.cuh
- candle-examples/examples/custom-ops/main.rs
Add an example with a custom cuda kernel.
> Kernel build example

- candle-examples/Cargo.toml
- candle-examples/examples/llama2-c/main.rs
- candle-examples/examples/llama2-c/model.rs
https://github.com/karpathy/llama2.c
> Add llama2.c as an example.

- candle-core/src/cuda_backend.rs
- candle-core/tests/tensor_tests.rs
- candle-kernels/src/binary.cu
- candle-kernels/src/binary_op_macros.cuh
- Add cuda kernels for comparison operations.
- Get the tests to run on both cpu and gpu.
> Add some cmp tests.

- candle-core/src/cpu_backend.rs
- candle-core/src/tensor.rs
- candle-core/tests/tensor_tests.rs
(and fix a bug in the cpu implementation)
> Add some testing for index-add

- candle-core/src/cuda_backend.rs
- candle-core/tests/tensor_tests.rs
- candle-kernels/src/indexing.cu
The initial version of this test segfaulted on cuda, this PR will include a bugfix.
> Add a test for scatter add.

- candle-flash-attn/build.rs
Add a `CANDLE_FLASH_ATTN_BUILD_DIR` environment variable that can be used to set a cache directory for the flash-attn compilation artifacts. This is useful as it takes multiple minutes to build.
> Specific cache dir for the flash attn build artifacts.

- candle-examples/examples/bigcode/main.rs
- candle-examples/examples/bigcode/model.rs
Work in progress for now, the goal would be to have starcoders running in candle.
> Add some Bigcode model

- candle-wasm-examples/llama2-c/Cargo.toml
- candle-wasm-examples/llama2-c/index.html
- candle-wasm-examples/llama2-c/src/app.rs
- candle-wasm-examples/llama2-c/src/lib.rs
- candle-wasm-examples/llama2-c/src/model.rs
- candle-wasm-examples/llama2-c/src/worker.rs
- Use some proper tokenizer.
- Add a prompt.
- Get the model code in line with the command line version.
> Wasm llama2 tweaks

- candle-core/src/ggml.rs
> Use the assert! function as it turns out to be const.

- Cargo.toml
- LICENSE-APACHE
- LICENSE-MIT
- candle-flash-attn/Cargo.toml
- candle-kernels/Cargo.toml
As noted by #329, the license files were missing, add them.
> Add the license files.

- README.md
- candle-book/src/guide/hello_world.md
- candle-book/src/guide/installation.md
fix repo link in readme and the book
> fix repo link

- candle-core/src/backend.rs
- candle-core/src/backprop.rs
- candle-core/src/cpu_backend.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/dummy_cuda_backend.rs
- candle-core/src/op.rs
- candle-core/src/storage.rs
- candle-core/src/tensor.rs
- candle-core/tests/pool_tests.rs
add support for max_pool2d and provide a simple test for it.
> add max_pool2d

- README.md
- candle-core/Cargo.toml
- candle-core/examples/cuda_basics.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/cudnn.rs
- candle-core/src/lib.rs
- candle-examples/Cargo.toml
Use cudnn for conv2d, this makes the stable diffusion example ~3x faster.
> Cudnn support

- candle-examples/examples/llama/main.rs
First, thanks for the project. For this PR, I have revised the llama example to support loading weights from the local folder as requested in #444. Besides, llama example can now support up to 4k outputs instead of fixed sample_len, i.e., dynamic output like ChatGPT.
Here is a simple test:
``` shell
cargo run --example llama --release --features cuda -- --local-weights /root/llama2chatweights/ --sample-len 4096 --prompt "Please give a short statement in 200 words about deep learning and its current state and trends in the next few years."
```
**Corresponding  Outputs:**
``` python
Args { cpu: false, npy: None, temperature: None, seed: 299792458, max_sample_len: 4096, no_kv_cache: false, prompt: Some("Please give a short statement in 200 words about deep learning and its current state and …
```
> Support local weights & dynamic outputs

- candle-examples/examples/llama/main.rs
- Look for the eos token rather than hardcoding it.
- Reduce the default prompt size now that it's not required anymore for it to be large enough.
- Display the token as they are produced using some simple heuristics.
- Print the prompt before the generated token so that things look nicer.
> Tweak the llama example.

- candle-core/src/ggml.rs
- Add a trait for the ggml types, similar to the c++ implementation.
- Use some basic implementations for this trait.
- Provide a matmul function (this is a work in progress).
> Basic quantization support

- candle-core/src/ggml.rs
- candle-core/tests/ggml_tests.rs
The goal of this PR is to get some minimal matmul to work with some associated test.
> More quantization support

- candle-examples/examples/llama/main.rs
- candle-examples/examples/llama/model.rs
Using the actual llama config intead of a hardcode one (enables >7b llama models)
> Using the real config from the hub when available.

- candle-book/src/guide/hello_world.md
- candle-book/src/inference/hub.md
- candle-core/src/tensor.rs
- candle-examples/examples/dinov2/main.rs
The motivation is mostly to check that we're not missing too many ops at the moment to handle state of the art vision models on top of LLMs.
> Add a vision transformer example (dino-v2).

- candle-core/examples/tensor-tools.rs
- candle-core/src/pickle.rs
- Change the `--format py-torch` flag to `--format pth`.
- Keep track of the storage size.
- Move the verbose flag where appropriate.
> Small tweaks to tensor-tools.

- candle-examples/examples/quantized/main.rs
Also separate the prompt stats from the post-prompt ones in the quantized example.
There was a discrepancy in how the rope embeddings were computed between the llama.cpp and the candle quantized implementation. After this fix, the resulting sequences with temperature 0 seem to be exactly in line, both for the f16 and the q4 versions.
The texts generated with some temperature are also a lot better than what they used to be.
```
./main -m ./models/7B/ggml-model-q4_0.bin --temp 0  --verbose-prompt -p 'This is a test' --repeat-penalty 1.0 -n 50
This is a test of the Emergency Broadcast System. This is only a test.
This is a test of the Emergency Broadcast System. This is only a test. If this had been an actual emergency, you would have been instructed where to go,
```
```
cargo run --example …
```
> Line up the llama.cpp implementation with the candle one.

- candle-nn/src/lib.rs
- candle-nn/src/var_builder.rs
- candle-nn/src/var_map.rs
Also fix some typo documentations.
> Move the VarMap to a separate file

- candle-examples/examples/whisper/main.rs
This is still a bit hacky as we don't sure that timestamp increase or apply the same heuristics as the openai original code but should provide some basic support for displaying timestamps.
> Improve the timestamps support in whisper

- candle-core/src/quantized/k_quants.rs
- candle-core/src/quantized/utils.rs
Reverts huggingface/candle#550
> Revert "Avoid some mut in quantized functions."

- candle-examples/examples/quantized/main.rs
add 
- TheBloke/Llama-2-7B-Chat-GGML
- TheBloke/Llama-2-13B-Chat-GGML
- TheBloke/Llama-2-70B-Chat-GGML
> add chat models in quantized example

- candle-core/tests/quantized_tests.rs
Adds mirrors of ggml's quantization and matmul unit tests to ensure the implementations match.
> Mirror GGML's unit tests

- candle-kernels/src/cast.cu
Currently complains because there's multiple cast possible.
Just forcing the actual cast type fixes it.
> Repairing cast bf16/f16

- candle-core/src/quantized/k_quants.rs
- Q4_1 vec_dot and quantization.
- Q5_1 quantization.
> More missing quantized bits.

- candle-core/src/backend.rs
- candle-core/src/backprop.rs
- candle-core/src/conv.rs
- candle-core/src/cpu_backend.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/dummy_cuda_backend.rs
- candle-core/src/op.rs
- candle-core/src/storage.rs
- candle-core/tests/conv_tests.rs
This is mostly to be able to support backprop for conv2d.
> Add conv-transpose.

- candle-nn/src/lib.rs
- candle-nn/src/ops.rs
Probably not very efficient at the moment.
> Add a Dropout layer

- candle-wasm-examples/yolo/README.md
- candle-wasm-examples/yolo/lib-example.html
- candle-wasm-examples/yolo/yoloWorker.js
Adapted current Yolo example to support yolo pose 
See live here: https://huggingface.co/spaces/radames/candle-yolo-wasm
> Add Yolo Pose to JS Example

- candle-nn/src/optim.rs
Note that this does not reset the momentum/var in adamw.
> Set the learning rate in the nn optimizers.

- candle-wasm-examples/llama2-c/README.md
- candle-wasm-examples/llama2-c/build-lib.sh
- candle-wasm-examples/llama2-c/lib-example.html
- candle-wasm-examples/llama2-c/llama2cWorker.js
- candle-wasm-examples/llama2-c/src/bin/m.rs
- candle-wasm-examples/llama2-c/src/worker.rs
* Expose model seq len, seed on Rust 
* Web Worker example loading model, running and aborting generation.
* Improved UI with seed, temp, max gen tokens
Demo: https://huggingface.co/spaces/radames/candle-llama2-c-rust-wasm
> Llama2c WASM UI improvements 

- candle-wasm-examples/llama2-c/lib-example.html
- candle-wasm-examples/llama2-c/llama2cWorker.js
- candle-wasm-examples/whisper/whisperWorker.js
- candle-wasm-examples/yolo/yoloWorker.js
This fix a caching issue, since HF models are not correctly cache, here using Cache API to store the models appropriately
update UI to change seq_len depending on model size
> WASM example fix

- candle-core/src/cuda_backend.rs
- candle-core/tests/tensor_tests.rs
> Fix cuda randn when generating an odd number of values.

- README.md
I added a useful libraries section which will contain links to various useful external libraries.
> Add useful libraries section

- candle-wasm-examples/llama2-c/lib-example.html
- candle-wasm-examples/whisper/lib-example.html
- candle-wasm-examples/yolo/lib-example.html
* limit max width
* remove listeners
> minor UI fixes

- candle-wasm-examples/segment-anything/README.md
- candle-wasm-examples/segment-anything/lib-example.html
- candle-wasm-examples/segment-anything/samWorker.js
- candle-wasm-examples/segment-anything/src/bin/m.rs
This PR add the vanilla JS SAM UI
* Rust: fix the iou conversion, send back image and mask data, it's helpful when rescaling the mask  
demo:
https://huggingface.co/spaces/radames/candle-segment-anything-anything-SAM-Wasm-demo
> Add SAM UI Demo

- README.md
- candle-wasm-examples/segment-anything/Cargo.toml
- candle-wasm-examples/segment-anything/samWorker.js
- candle-wasm-examples/segment-anything/src/bin/m.rs
Add SAM links to main README
Update to use serde_wasm_bindgen, slightly better performance 🤔
> Update README + SAM

- candle-examples/examples/wuerstchen/main.rs
- candle-transformers/src/models/wuerstchen/ddpm.rs
- candle-transformers/src/models/wuerstchen/mod.rs
Also add the specialized DDPM scheduler.
> Fix the W clip embeddings.

- README.md
> update link to t5

- candle-wasm-examples/t5/utils.js
> smaller t5 models quantized

- candle-examples/examples/yolo-v8/main.rs
- candle-examples/examples/yolo-v8/model.rs
This should make performance investigation easier.
> Add tracing to yolo-v8.

- candle-wasm-examples/llama2-c/lib-example.html
- candle-wasm-examples/llama2-c/llama2cWorker.js
fix for first token 
minor ui changes
> fix firstToken on llama2c wasm

- Cargo.toml
- README.md
- candle-wasm-examples/phi/Cargo.toml
- candle-wasm-examples/phi/README.md
- candle-wasm-examples/phi/build-lib.sh
- candle-wasm-examples/phi/index.html
- candle-wasm-examples/phi/phiWorker.js
- candle-wasm-examples/phi/src/bin/m.rs
- candle-wasm-examples/phi/src/lib.rs
Add Phi quantized model as Wasm module example
@LaurentMazare if you would like to test, I'll finish the PR tomorrow PST. It still needs a blurb description, but overall I think all the features are there. Maybe a better default prompt?
> Phi 1.5 wasm module

- candle-core/src/tensor.rs
Hi,
Guessing this was supposed to be like this?
Thanks.
> fix: fixes slice_scatter dim type

- candle-wasm-examples/segment-anything/Cargo.toml
- candle-wasm-examples/segment-anything/lib-example.html
- candle-wasm-examples/segment-anything/samWorker.js
- candle-wasm-examples/segment-anything/src/bin/m.rs
Allow user to add multiple point on the image.
based on issue #989
> [segment-anything] add multi point logic for demo site

- candle-wasm-examples/segment-anything/lib-example.html
Demo Updated: https://huggingface.co/spaces/radames/candle-segment-anything-wasm
> [SAM] Add undo button and background point mode

- candle-book/src/simplified.rs
Sorry. This is cosmetics improvement + misspeling fix
Checked via mdbook serve
> small misspeling and polish fix

- candle-examples/examples/quantized-t5/main.rs
These are small changes to make it possible to use models other than [lmz/candle-quantized-t5](https://huggingface.co/lmz/candle-quantized-t5/tree/main). For example, to use [jbochi/candle-coedit-quantized](https://huggingface.co/jbochi/candle-coedit-quantized), one can run:
```shell
$ cargo run --example quantized-t5 --release  -- \
--model-id "jbochi/candle-coedit-quantized" \
--weight-file "model-xl.gguf" \
--config-file "config-xl.json" \
--prompt "Rewrite to make this easier to understand: Note that a storm surge is what forecasters consider a hurricane's most treacherous aspect." \
--temperature 0
...
Note that a storm surge is what forecasters consider a hurricane's most dangerous part.
```
It still supports local files, and will use `config.json` and `model.gguf` from the remote …
> Add quantized t5 args for weight and config

- candle-core/src/cuda_backend.rs
- candle-core/tests/tensor_tests.rs
- candle-kernels/src/indexing.cu
Hi,
I think this might be caused possibly after https://github.com/huggingface/candle/pull/1022/files#diff-2f1279372ccba2e7f8d23f07416dccac61ff6b838532bdf5ed06519ee1005d86R894 ?
> fix: fix index_select cuda kernel for src target dim different than ids dim when selecting dim > 0

- candle-wasm-examples/segment-anything/lib-example.html
@radames I've add a download button and the download function for the cutout image!
https://github.com/huggingface/candle/assets/10290616/5503f55e-623e-402a-9f51-482c9b148a27
> feat: [SAM] able to download the result as png

- candle-examples/examples/stable-diffusion/main.rs
> Override the repo for SDXL f16 vae weights.

- candle-kernels/src/cast.cu
This PR reworks the cuda casting logic and in particular adds kernel for conversion to/from u8.
> Rework the cuda casting.

- candle-transformers/src/models/mixformer.rs
- candle-wasm-examples/phi/index.html
- candle-wasm-examples/phi/phiWorker.js
- candle-wasm-examples/phi/src/bin/m.rs
Made the config load from a file
Demo
https://huggingface.co/spaces/radames/Candle-Phi-1.5-Wasm
> [Wasm] Add puffin phi model to wasm

- candle-core/src/error.rs
- candle-core/src/tensor.rs
Hi,
While working on implementing the Swin model as part of the [Nougat issue](https://github.com/huggingface/candle/issues/1070) I quickly ran into missing the `meshgrid` tensor operator. Hence this PR.
Let me know what you think!
> Implemented meshgrid

- candle-examples/examples/jina-bert/main.rs
- candle-transformers/src/models/bert.rs
- candle-transformers/src/models/jina_bert.rs
- candle-transformers/src/models/mod.rs
[model card](https://huggingface.co/jinaai/jina-embeddings-v2-base-en)
> Add the jina-bert embeddings model.

- candle-transformers/src/models/jina_bert.rs
- Correct the max-position-embeddings to be 8192.
- Fix the alibi slopes computation (in line with mpt).
> Fixes for jina-bert.

- candle-examples/examples/vgg/README.md
- candle-examples/examples/vgg/main.rs
- candle-transformers/src/models/mod.rs
- candle-transformers/src/models/vgg.rs
This PR is a follow up to https://github.com/huggingface/candle/pull/1209 and implemented VGG13/16/19 and relies on `hf-hub` for the models
> feat: implement VGG13, VGG16 and VGG19

- candle-core/src/backend.rs
- candle-core/src/backprop.rs
- candle-core/src/conv.rs
- candle-core/src/cpu_backend.rs
- candle-core/src/cuda_backend.rs
- candle-core/src/dummy_cuda_backend.rs
- candle-core/src/op.rs
- candle-core/src/storage.rs
This just adds the boilerplate and params for the op, cpu/cuda implementations to follow.
> Add the conv-transpose1d op.

- candle-core/src/quantized/gguf_file.rs
The decoding logic is identical to v2, this assumes little endian models on a little endian platform.
> Allow using gguf-v3 files.

- candle-core/src/backprop.rs
- candle-core/tests/grad_tests.rs
adds backprop for elu and test to compare with pytorch output
> feat: add backprop for elu

- candle-onnx/src/eval.rs
And also add support for convolutions.
> Refactor the onnx attribute getters.

- README.md
- candle-examples/examples/quantized-t5/README.md
- candle-examples/examples/t5/README.md
This updates the documentation as suggested in https://github.com/huggingface/candle/pull/1285#issuecomment-1797810032
> Add info about MADLAD-400 in readme files

- candle-transformers/src/models/quantized_t5.rs
- candle-transformers/src/models/t5.rs
So sorry about that. This fixes the error I introduced in https://github.com/huggingface/candle/commit/508f811b93035f076e18778fe08106f15abfa8a7#r132039827
Thank you @bm777 for letting me know.
> Fix bug introduced in madlad PR

- candle-onnx/src/eval.rs
i think should be add with negative axis
> fix: negative axis

- candle-examples/examples/yolo-v8/README.md
Fix image path used in yolo-v8 pose estimation example
> Fix pose estimation image path

- candle-transformers/src/models/stable_diffusion/ddim.rs
- candle-transformers/src/models/stable_diffusion/euler_ancestral_discrete.rs
- candle-transformers/src/models/stable_diffusion/mod.rs
- candle-transformers/src/models/stable_diffusion/schedulers.rs
- candle-transformers/src/models/stable_diffusion/utils.rs
This PR add Euler Ancestral Discrete Scheduler and add support for timestep spacing.
They are used in Stable Diffusion XL Turbo. (I will submit another PR for that)
> Add Euler Ancestral Discrete Scheduler

- candle-nn/src/optim.rs
Wasn't sure how involved this should be but this is the simplest way I thought of. Open for suggestions or improvements. Thank you!
Resolves #1448
> Expose AdamW parameters

- candle-transformers/src/models/mistral.rs
Add config for [amazon/MistralLite](https://huggingface.co/amazon/MistralLite/blob/main/config.json).
> add config_amazon_mistral_lite

- candle-core/src/metal_backend.rs
Hi,
Thanks for adding Metal support!
Been trying it out and updating these error messages helped debug and understand what's supported and what not yet.
Hope it help others too.
> Improves metal's not implemented error messages

- candle-core/src/metal_backend.rs
- candle-metal-kernels/src/binary.metal
- candle-metal-kernels/src/cast.metal
- candle-metal-kernels/src/lib.rs
- candle-metal-kernels/src/reduce.metal
- candle-metal-kernels/src/ternary.metal
- candle-metal-kernels/src/unary.metal
Plan to complete with at least the same i64 support current in cuda kernels.
> Metal: i64 basic support

- candle-examples/examples/reinforcement-learning/README.md
- candle-examples/examples/reinforcement-learning/ddpg.rs
- candle-examples/examples/reinforcement-learning/main.rs
- candle-examples/examples/reinforcement-learning/policy_gradient.rs
Inspired by the discussion in [this issue](https://github.com/huggingface/candle/issues/1065) and the [Reinforcement Learning examples in `tch-rs`](https://github.com/LaurentMazare/tch-rs/tree/main/examples/reinforcement-learning), this PR adds `policy_gradient.rs`.
Considering that the only available example was `ddpg.rs`, this code modifies `main.rs` to make it possible to choose which one of the two `reinforcement-learning` examples to run.
So, after these changes:
- The `main` function in `main.rs` is now the `run` function in `ddpg.rs`
-  `policy_gradient.rs` has its own `run` function 
- `main.rs` reads from command line and runs the desired `run` function
- `README.md` tells how to run the different examples
To make it easier to launch the examples from `main.rs`, the following …
> Add Policy Gradient to Reinforcement Learning examples

- candle-core/src/pickle.rs
> Handle start-offset when loading a tensor from a pickle file.

- candle-transformers/src/models/bert.rs
- candle-transformers/src/models/bigcode.rs
- candle-transformers/src/models/falcon.rs
- candle-transformers/src/models/llama.rs
- candle-transformers/src/models/whisper/model.rs
Remove a few copies of embedding.
> Use candle_nn::embedding instead of local copies in a few models.

- candle-examples/examples/repvgg/README.md
- candle-examples/examples/repvgg/main.rs
- candle-transformers/src/models/mod.rs
- candle-transformers/src/models/repvgg.rs
RepVGG model inference implementation
https://arxiv.org/abs/2101.03697
> Add RepVGG model.

- candle-core/Cargo.toml
- candle-core/src/metal_backend.rs
- candle-metal-kernels/Cargo.toml
- candle-metal-kernels/src/cast.metal
- candle-metal-kernels/src/indexing.metal
- candle-metal-kernels/src/tests.rs
- extended bf16 cast support and testing
- added tests for bf16 binary ops
- added `is_u32_bf16` and `is_u8_bf16`
- exposed new + some existing kernels to candle-core's metal backend
> feat(metal/bf16): additional cast support for bf16

- candle-core/src/lib.rs
Some recent discord discussions showed some interest for this trait being exposed and potentially implemented in other libraries, hence trying it out with this feature.
> Expose the ndarray trait.

- candle-examples/examples/mobileone/README.md
- candle-examples/examples/mobileone/main.rs
- candle-transformers/src/models/mobileone.rs
- candle-transformers/src/models/mod.rs
Another model using structural reparameterization.
> Add MobileOne model.

- candle-onnx/src/eval.rs
- candle-onnx/tests/ops.rs
onnx: add the Flatten operator.
ref: https://github.com/onnx/onnx/blob/8a6b70f0adcff5409b8cd65883bbbea7d6c4f4e1/onnx/reference/ops/op_flatten.py#L11
> onnx: add the Flatten operator.

- candle-core/src/tensor.rs
> add `roll` function to tensor

- candle-transformers/src/models/trocr.rs
Also support `tie_word_embeddings` as it's required for the `large-printed` model to work.
> Support sinusoidal embeddings in trocr.

- candle-core/src/cuda_backend.rs
- candle-core/tests/conv_tests.rs
- candle-kernels/src/conv.cu
Very naive support re-using the ConvTranspose2d kernel.
> ConvTranspose1d cuda support.

- candle-core/src/quantized/ggml_file.rs
- candle-core/src/quantized/metal.rs
- candle-core/src/quantized/mod.rs
- candle-transformers/src/models/quantized_llama.rs
- Decided to add surface in order to change only internal functions, we could also pass device
to more functions instead.
> Fixing quantized llama demo on metal, by removing all hardcoded values for Cpu.

- candle-examples/examples/rwkv/main.rs
fix rwkv example eos token, mentioned by issue #1755
> fix rwkv example eos token

- candle-transformers/src/models/quantized_stable_lm.rs
- candle-transformers/src/models/stable_lm.rs
> fix: update StableLM config

- candle-examples/examples/stable-diffusion/main.rs
Per suggestion in https://github.com/huggingface/candle/pull/1811#issuecomment-1983079119
> Add a --seed argument to the stable-diffusion example.

- candle-core/src/layout.rs
This should make it a bit easier to implement custom kernels that have to tweak the layout.
> Expose a couple layout methods.

- candle-core/src/quantized/mod.rs
> Fix dequantization.

- candle-examples/examples/whisper/main.rs
Tested using the following example:
```
cd candle/candle-examples/examples/whisper
cargo run --example whisper --release --features symphonia -- --model distil-large-v3
```
Output:
```
No audio file submitted: Downloading https://huggingface.co/datasets/Narsil/candle_demo/blob/main/samples_jfk.wav
pcm data loaded 176000
loaded mel: [1, 128, 3000]
english: 0.9849657
portuguese: 0.0024733297
spanish: 0.0019878238
russian: 0.001226182
french: 0.0011861552
0.0s -- 30.0s:  And so, my fellow Americans, ask not what your country can do for you. Ask what you can do for your country.
```
> Add support for distil-large-v3

- candle-examples/examples/mistral/main.rs
- candle-transformers/src/models/mistral.rs
- candle-transformers/src/models/quantized_mistral.rs
- Add the repo for the instruct variants.
- Make the sliding window parameter optional (set to null in 0.2 models).
> Support more mistral models.

- candle-kernels/src/reduce.cu
- candle-metal-kernels/src/lib.rs
- candle-metal-kernels/src/reduce.metal
- candle-nn/src/rotary_emb.rs
- candle-nn/tests/ops.rs
On the mistral quantized model (7b-q4k):
- Metal (M2 Pro 16GB): 19.2 token/s -> 22.3 token/s.
- Cuda (RTX 2080): 28.9 token/s -> 29.5 token/s.
> Contiguous variant of the rope kernel.

- candle-nn/src/rotary_emb.rs
> Fix detail in new RoPE implementation

- candle-core/src/shape.rs
- candle-transformers/src/models/dinov2.rs
Also be more lenient on the layout on dimension that only have one element.
> Another fix for squeezing.

- candle-transformers/src/models/stable_diffusion/attention.rs
Force a copy of the rhs of a matmul to get around the issue in #1992 .
> Stable diffusion fix.

- candle-nn/Cargo.toml
- candle-nn/benches/bench_main.rs
- candle-nn/benches/benchmarks/conv.rs
- candle-nn/benches/benchmarks/layer_norm.rs
- candle-nn/benches/benchmarks/mod.rs
Been doing some work on optimizing the layernorm and conv2d, figured I can get this in earlier than when I submit a PR for those!
Let me know if you have any feedback, it's essentially a copy of the core create's bench marks
> Add benchmarks for the candle-nn package

- candle-wasm-examples/moondream/Cargo.toml
- candle-wasm-examples/moondream/README.md
- candle-wasm-examples/moondream/build-lib.sh
- candle-wasm-examples/moondream/code.js
- candle-wasm-examples/moondream/index.html
- candle-wasm-examples/moondream/moondreamWorker.js
- candle-wasm-examples/moondream/src/bin/m.rs
- candle-wasm-examples/moondream/src/lib.rs
Here is our first attempt, @LaurentMazare. If you have any insights on how to make the vision encoder faster, we'd appreciate
cc @santiagomed and @vikhyat are investigating why the first token/image step is slower than the subsequent tokens.
The output varies on hardware, from 2-4 tokens/sec, and it takes approximately 60 seconds for the image embedding step.
Also, while I'm caching the image embedding for later prompts, I'm not sure if a cache cleanup step is missing to reuse the image embedding efficiently.
Demo running https://huggingface.co/spaces/radames/Candle-Moondream-2
> Moondream WASM

- README.md
Added link to the Coursera ML algorithm implementations as an external resource.
> Added link to the Coursera ML algorithm implementations

- candle-transformers/src/models/mixformer.rs
- candle-transformers/src/models/moondream.rs
Current trace running on GPU:
Most of the time is spent in the first mixformer call, so processing the prompt including the image embeddings. Zooming on these:
A lot of time is spent in the conditional mask, I'll make some tweaks to it as it should be straightforward to optimize. Besides this, the activation function in the mlp seems to also take a bunch of time.
> Moondream tracing.

- candle-examples/examples/recurrent-gemma/README.md
- candle-examples/examples/recurrent-gemma/main.rs
- candle-transformers/src/models/mod.rs
- candle-transformers/src/models/recurrent_gemma.rs
This is a pretty barebone implementation based on the transformers one. It is not much optimized at this stage but has been lined up so that logits match the python implementation (using `f32` on both sides).
> Add the recurrent-gemma model.

- candle-examples/examples/quantized/main.rs
So far I've found quantized versions here: https://huggingface.co/QuantFactory/Meta-Llama-3-8B-GGUF and the tokenizer here: https://huggingface.co/unsloth/llama-3-8b/tree/main
> Add support for llama3 on the quantized example

- candle-examples/examples/llama_multiprocess/main.rs
> Only download the weights in the main process (and not in the child processes).

- candle-onnx/src/eval.rs
- candle-onnx/tests/ops.rs
Adds the RandomUniform and Exp operators together with tests for them.
> candle-onnx: add operators RandomUniform and Exp

- candle-examples/examples/olmo/README.md
- candle-examples/examples/olmo/main.rs
- candle-transformers/src/models/mod.rs
- candle-transformers/src/models/olmo.rs
This PR add [OLMo](https://huggingface.co/allenai/OLMo-1.7-7B-hf) models to `candle-transformers`.
OLMo is a series of Open Language Models designed to enable the science of language models with all training details open sourced.
> Add Olmo models

- candle-core/src/lib.rs
- candle-core/src/metal_backend/mod.rs
- candle-core/src/sort.rs
- candle-core/tests/tensor_tests.rs
- candle-kernels/src/lib.rs
- candle-kernels/src/sort.cu
- candle-metal-kernels/src/lib.rs
- candle-metal-kernels/src/quantized.metal
- candle-metal-kernels/src/sort.metal
- candle-transformers/src/models/qwen2.rs
- candle-transformers/src/models/qwen2_moe.rs
In this PR, this is done via a `CustomOp1` but it's a bit unclear where this should live. I've put it in candle-core for now but maybe it belongs more in candle-nn?
> Add argsort.

- candle-nn/src/var_builder.rs
Also implement SimpleBackend for SliceSafetensors
> Fix VarBuilder::from_slice_safetensors

- candle-onnx/src/eval.rs
- candle-onnx/tests/ops.rs
The implementation is very similar to the RandomUniform operator I've wrote earlier.
I wasn't sure how to test the result, I didn't want to use a statistical test as they might fail if we are very unlucky, so I'm just testing for the uniqueness of the values. If it's not ok please let me know.
> Add RandomNormal ONNX operator

- candle-examples/examples/phi/main.rs
Unlike Phi3-small, this is the same architecture as Phi3-mini
> Add Phi-3 Medium

- candle-core/src/metal_backend/mod.rs
- candle-metal-kernels/src/tests.rs
- candle-nn/benches/benchmarks/layer_norm.rs
Make sure we have where_u32_f32 for metal
> add where_cond f32 for metal

- candle-onnx/src/eval.rs
- candle-onnx/tests/ops.rs
I've noticed that some simple unary operators were missing.
> ONNX: Add Floor and Ceil

- candle-examples/examples/beit/main.rs
- candle-transformers/src/models/beit.rs
Hi,
Following the PS comment in #2305 , I fixed the Beit code and added the magic function 'gen_relative_position_index()'.
I also updated the weights on Hugging Face accordingly, by removing the unnecessary tensor parameter (relative_position_index).
Beit code is fine for now.
Thank you for your time & sorry for the inconvenience.
> Beit fix: Add the gen_relative_position_index() function

- README.md
- candle-examples/examples/mobilenetv4/README.md
- candle-examples/examples/mobilenetv4/main.rs
- candle-examples/src/imagenet.rs
- candle-transformers/src/models/mobilenetv4.rs
- candle-transformers/src/models/mod.rs
Since these models can use images of different resolutions as input I've made the load_image() helper more generic.
> Add Mobilenet v4

- candle-examples/examples/jina-bert/main.rs
- candle-transformers/src/models/jina_bert.rs
Jina Bert Example did not show mean pooled output and was not able to run other models than the English one without having it locally
> Jina Bert Example fix and more configuration

- candle-examples/examples/flux/main.rs
Add the [FLUX1-dev](https://huggingface.co/black-forest-labs/FLUX.1-dev) model too, the default is still schnell as it's a lot faster.
Sample generated image:
```bash
cargo run --features cuda --example flux -r -- \
--height 1024 --width 1024 \
--prompt "a rusty robot walking on a beach holding a small torch, the robot has the word "rust" written on it, high quality, 4k" \
--model dev
```
> Support the FLUX.1-dev model too.

- .github/workflows/python.yml
- .github/workflows/rust-ci.yml
> fix: usage of `actions/checkout@v2`

- candle-examples/examples/based/README.md
- candle-examples/examples/based/main.rs
- candle-transformers/src/models/based.rs
- candle-transformers/src/models/mod.rs
Small LLMs based on an interesting architecture. 
https://hazyresearch.stanford.edu/blog/2024-03-03-based
> Add Based LLM from Hazy Research.

- candle-examples/examples/llama_multiprocess/main.rs
Just a simple fix to be able to run `llama_multiprocess` example.
> Fix build issue in EOS Token in llama-multiprocess

- README.md
Hello. Added a link to the licenses
> Docs: Added a link to the licenses

- candle-transformers/src/models/based.rs
- candle-transformers/src/models/bert.rs
- candle-transformers/src/models/bigcode.rs
- candle-transformers/src/models/flux/mod.rs
- candle-transformers/src/models/pixtral/mod.rs
As discussed in a Discord thread.
> Module Docs

- candle-kernels/src/quantized.cu
Use the same hack to provide `__dp4a` to older architectures as in llama.cpp, see [common.cuh](https://github.com/ggerganov/llama.cpp/blob/557924f22237c76387a39c4db5abae154d57e754/ggml/src/ggml-cuda/common.cuh#L317-L319).
> Import the ggml_cuda_dp4a function.

- candle-onnx/src/eval.rs
- candle-onnx/tests/ops.rs
Implementation of sign operation.
https://onnx.ai/onnx/operators/onnx__Sign.html
> Onnx Support for Sign operation #2641

- candle-examples/examples/flux/main.rs
- candle-examples/examples/glm4/README.org
- candle-examples/examples/glm4/main.rs
Simplify the GLM4 example so as to be closer to other examples: handle a single prompt rather than an interactive session.
> Streamline the glm4 example.

- candle-examples/examples/phi/main.rs
Add phi-4-mini to the phi example
> phi-4-mini

- candle-transformers/src/models/modernbert.rs
Hi! I added a SequenceClassification for ModernBert models. And I tested that implementation on my classifier model on [HuggingFace](https://huggingface.co/Mnwa/modernbert-toxic-russian)
> Add ModernBert SequenceClassification

- candle-examples/examples/gemma/main.rs
- Updates the Gemma example to include Gemma 3 1b instruction tuned.
> Add Gemma 3 1b IT toe Gemma examples

- candle-examples/examples/whisper-microphone/main.rs
Changed
`rand::distributions::Distribution` to `rand::distr::Distribution`
and
`rand::distributions::WeightedIndex` to `rand::distr::weighted::WeightedIndex`
> Fixed rand imports for whisper-microphone example.

- candle-datasets/src/vision/cifar.rs
Currently, `candle_datasets::vision::cifar::load()` returns images of all 0s because of a type mismatch error. The image dimensions also need to be permuted. This is noted in https://github.com/huggingface/candle/issues/2632, an issue that I encountered recently as well. @cschin proposed a solution, which is implemented here. The permutation dimensions are slightly different to uphold the `(C, H, W)` conv layer convention, but doesn't matter given the symmetry of CIFAR10 square images.
> Fix CIFAR10 dataset types and dimension ordering

- candle-examples/examples/quantized-qwen2-instruct/main.rs
From [unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF](https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF)
`cargo run --example quantized-qwen2-instruct  --release -- --which deepseekr1-qwen7b --prompt "Write a function to count prime numbers up to N.`
> Added DeepseekR1 Qwen7B variant to quantized-qwen2-instruct example

- candle-examples/examples/quantized/main.rs
From [unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF](https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF)
`cargo run --example quantized --release -- --which deepseekr1-llama8b --prompt "Lebesgue's integral is superior to Riemann's because "`
> Added Deepseekr1 Llama8b variant to quantized example

- README.md
- candle-book/CONTRIBUTING.md
- candle-book/src/README.md
- candle-book/src/SUMMARY.md
- candle-book/src/guide/installation.md
- candle-book/src/guide/mnist/intro.md
- candle-book/src/guide/mnist/modeling.md
- candle-book/src/guide/mnist/saving_loading.md
- candle-book/src/guide/mnist/training.md
Thought I'd update the documentation to familiarize myself with mdbook:
- Added goals from project README to candle-book introduction because I think It is a good overview.
- Updated Installation
- Added other variants, like metal, and MKL
- Reformatted to reduce repetition.
- Added simple `CONTRIBUTING.md` that describes how to modify and check the book locally using `mdbook`.
- Updated the mnist tutorial
- Restructured the guide into 3 sections (modeling, training, and saving/loading)
- Improved code examples with more comments and explanations
> Updated candle-book: Introduction, Installation, MNIST guide, and added CONTRIBUTING.md

- candle-transformers/src/models/quantized_gemma3.rs
While working on the fixes for #2917, I got curious about whether those changes could also benefit the quantized version of the model.
Implementing the correct sliding masking led to a slight performance improvement, so I started experimenting further. I noticed that the [GGUF file](https://huggingface.co/google/gemma-3-4b-it-qat-q4_0-gguf?show_file_info=gemma-3-4b-it-q4_0.gguf) doesn’t include a sliding window RoPE frequency or a sliding window type (the parameter that describes the ratio of sliding layers to global layers). So I tried manually setting it to the value used by the non-quantized Gemma3, ignoring the scale_factor from the GGUF metadata.
Surprisingly, this made a significant difference, the model became noticeably less rambly, terminated faster, repeated itself less, and …
> Fixed Quantized Gemma3 Model and example

- candle-core/src/metal_backend/mod.rs
This dtype check is (afaik) a remnant from when we had two different implementations.
> Remove redundant mlx gemm dtype check

- candle-core/src/tensor.rs
Currently `Tensor::full` returns a broadcasted version of a scalar. This is a bit error prone as `zeros` or `ones` return a full contiguous tensor, and this can have some performance implications.
The old behavior can still be obtained by doing `Tensor::full(foo, (), dev)?.broadcast_as(shape)?`.
> Switch Tensor::full to return a contiguous tensor.

- candle-examples/examples/onnx/main.rs
- candle-onnx/src/eval.rs
> [!Warning]
> Incomplete
From https://github.com/huggingface/candle/issues/2876
> Add Resize to onnx ops

- candle-examples/examples/olmo/README.md
- candle-examples/examples/olmo/main.rs
- candle-transformers/src/models/mod.rs
- candle-transformers/src/models/olmo2.rs
Use the 1B model in the example.
> Olmo 2 model

- .github/workflows/rust-ci.yml
From https://github.com/briansmith/ring/discussions/2528
> CI: Fixed Apple Arm Error

- Cargo.toml
Update cudarc to v0.17.3 which has support for CUDA 13.
> Add CUDA 13 support

- candle-metal-kernels/src/err.rs
- candle-metal-kernels/src/metal/command_buffer.rs
- candle-metal-kernels/src/metal/commands.rs
Waiting on #3106 before merging
> [Metal] Improve wait_for_completed command buffers locking
